// Country-specific animal spotter lists, kept in their own file so
// the main adventurePackData blocks don't bloat. Merged into the
// pack data by getPackData() at request time.
//
// Each country has 4–6 spottable animals. The first 3–4 should be
// realistic for a casual visit (urban / common rural / well-known
// zoo or sanctuary species). Older-only ones are rarer or trickier
// and only appear when the kid switches to older-mode.

import type { AnimalItem } from './adventurePackTypes'

export const ANIMALS_BY_SLUG: Record<string, AnimalItem[]> = {
  // ── EUROPE ──────────────────────────────────────────────────────
  france: [
    { emoji: '🕊️', name: 'Feral pigeon', description: 'In every square, café and railway station. Bread crumbs welcome.' },
    { emoji: '🐶', name: 'Pampered city dog', description: 'Often small, often in a handbag, often in restaurants. Paris has more dogs than children.' },
    { emoji: '🐮', name: 'Cow in a meadow', description: 'Especially Charolais (cream-white) or Normande (brown-and-white) in the countryside.' },
    { emoji: '🦊', name: 'Red fox', description: 'Watch hedgerows at dusk in the countryside, or city parks at night.' },
    { emoji: '🐦‍⬛', name: 'Common magpie', description: 'Black-and-white bird with a long tail, very chatty. Loves shiny things.' },
    { emoji: '🐎', name: 'Camargue horse', description: 'White semi-wild horse of the Rhône delta. Born dark, turning white as it ages.', olderOnly: true },
    { emoji: '🦔', name: 'Hedgehog', description: 'Trundling through a hedge or garden at dusk. Mostly summer.', olderOnly: true },
  ],
  spain: [
    { emoji: '🕊️', name: 'Feral pigeon', description: 'Every plaza, every cathedral square, every tapas terrace.' },
    { emoji: '🦅', name: 'White stork', description: 'On almost every church tower in central / western Spain. Huge nests of sticks.' },
    { emoji: '🐂', name: 'Toro / fighting bull', description: 'Bred on dehesa pastures across Andalusia and Extremadura. Watch for the Osborne bull billboards too.' },
    { emoji: '🦩', name: 'Greater flamingo', description: 'Pink wading birds at coastal salt lagoons (Doñana, Fuente de Piedra).' },
    { emoji: '🐐', name: 'Spanish ibex', description: 'Wild goats with curved horns on rocky slopes in the Sierra Nevada and Pyrenees.', olderOnly: true },
    { emoji: '🐱', name: 'Iberian lynx', description: 'Critically endangered wild cat with ear tufts. Real sightings are rare — count zoo or sanctuary too.', olderOnly: true },
  ],
  portugal: [
    { emoji: '🕊️', name: 'Feral pigeon', description: 'Lisbon\'s squares are full of them. Statues come pre-decorated.' },
    { emoji: '🦅', name: 'White stork', description: 'Big nests on chimneys and church towers across Alentejo and the Algarve.' },
    { emoji: '🦊', name: 'Red fox', description: 'In hedgerows at dusk in the countryside, sometimes in suburban gardens.' },
    { emoji: '🐗', name: 'Wild boar', description: 'Mostly nocturnal but increasingly bold in country villages and Lisbon\'s outskirts.' },
    { emoji: '🦌', name: 'Red deer', description: 'In the cork-oak dehesa landscapes and Peneda-Gerês National Park.', olderOnly: true },
    { emoji: '🐬', name: 'Common dolphin', description: 'Pods riding the bow wave off the Algarve and Sado coastlines.', olderOnly: true },
  ],
  'united-kingdom': [
    { emoji: '🦊', name: 'Urban fox', description: 'In gardens, dustbins, suburban streets at night. The most British wild animal.' },
    { emoji: '🐦‍⬛', name: 'Common magpie', description: '"One for sorrow, two for joy" — black-and-white birds you greet for luck.' },
    { emoji: '🐿️', name: 'Grey squirrel', description: 'In every park. Cheeky, fast, will steal your sandwich.' },
    { emoji: '🐑', name: 'Sheep in a field', description: 'There are more sheep than people in Wales and parts of Scotland.' },
    { emoji: '🦌', name: 'Red or roe deer', description: 'Roe deer slip across country roads at dawn. Red deer in Scottish glens.' },
    { emoji: '🐿️', name: 'Red squirrel', description: 'Rare now, mostly in Scotland and Anglesey. Tufty ears, ginger fur.', olderOnly: true },
    { emoji: '🦔', name: 'Hedgehog', description: 'Snuffling along a hedge at dusk. Numbers have crashed — celebrate every one.', olderOnly: true },
  ],
  germany: [
    { emoji: '🕊️', name: 'Feral pigeon', description: 'Every train station, every market square, every beer-garden floor.' },
    { emoji: '🐦‍⬛', name: 'Hooded crow', description: 'Grey-and-black crow on the rooftops and parks, especially in the east.' },
    { emoji: '🦊', name: 'Red fox', description: 'In Berlin you might see one trotting down a city street at 4am.' },
    { emoji: '🦌', name: 'Roe deer', description: 'Small reddish-brown deer in fields at the forest edge, often at dusk.' },
    { emoji: '🐗', name: 'Wild boar', description: 'Common in German forests and surprisingly bold around suburbs.', olderOnly: true },
    { emoji: '🦅', name: 'White stork', description: 'Returning to chimney-top nests every spring after wintering in Africa.', olderOnly: true },
  ],
  belgium: [
    { emoji: '🕊️', name: 'Feral pigeon', description: 'Grand-Place pigeons in Brussels expect their share of your frites.' },
    { emoji: '🦆', name: 'Mallard duck', description: 'Paddling on Bruges canals and Ghent\'s rivers.' },
    { emoji: '🐶', name: 'Belgian sheepdog', description: 'Tervuren or Groenendael — long-haired black or fawn herding dogs.' },
    { emoji: '🦢', name: 'Mute swan', description: 'Bruges canals are famous for their swans, kept since the 1400s.' },
    { emoji: '🐦‍⬛', name: 'Eurasian magpie', description: 'Chatty black-and-white bird in every Belgian back garden.' },
    { emoji: '🦌', name: 'Red deer', description: 'In the Ardennes forests in the south of the country.', olderOnly: true },
  ],
  netherlands: [
    { emoji: '🦆', name: 'Mallard duck', description: 'On every canal in Amsterdam and every park pond in the country.' },
    { emoji: '🐮', name: 'Holstein-Friesian cow', description: 'Black-and-white dairy cow in flat green fields between the cities.' },
    { emoji: '🦢', name: 'Mute swan', description: 'Gliding on canals and waterways, sometimes hissy if you get too close.' },
    { emoji: '🐑', name: 'Texel sheep', description: 'The plump white sheep on Texel and other Wadden Islands.' },
    { emoji: '🐎', name: 'Konik pony', description: 'Semi-wild grey-dun ponies in the Oostvaardersplassen wetland nature reserve.', olderOnly: true },
    { emoji: '🦅', name: 'White stork', description: 'Reintroduced and now common again in summer in rural Holland.', olderOnly: true },
  ],

  // ── ASIA ────────────────────────────────────────────────────────
  morocco: [
    { emoji: '🐱', name: 'Medina cat', description: 'There are an unbelievable number of medina cats, especially in Fez. Friendly, well-fed by locals.' },
    { emoji: '🫏', name: 'Working donkey', description: 'The only delivery vehicle that fits down the narrowest medina alleys.' },
    { emoji: '🦅', name: 'White stork', description: 'Big nests of sticks on the tops of old palaces, mosques and lamp-posts.' },
    { emoji: '🐐', name: 'Tree-climbing goat', description: 'In the Atlas foothills, goats climb argan trees to eat the fruit. Yes, really.' },
    { emoji: '🐪', name: 'Dromedary camel', description: 'One hump. Around the Sahara dunes, ridden by Berber guides.', olderOnly: true },
    { emoji: '🐒', name: 'Barbary macaque', description: 'Tail-less monkeys in the cedar forests of the Middle Atlas, especially near Azrou.', olderOnly: true },
  ],
  egypt: [
    { emoji: '🕊️', name: 'Rock dove', description: 'Egypt domesticated pigeons thousands of years ago — they\'re everywhere.' },
    { emoji: '🐪', name: 'Dromedary camel', description: 'Beside every pyramid, sphinx and tourist site. Riding them is optional.' },
    { emoji: '🐈', name: 'Egyptian street cat', description: 'Sacred for thousands of years. Still in every alley, still acting like it owns the place.' },
    { emoji: '🫏', name: 'Working donkey', description: 'Carrying sugarcane, vegetables, kids — still doing the work of small trucks in rural Egypt.' },
    { emoji: '🦅', name: 'Black kite', description: 'Forked-tail bird of prey circling above Cairo and the Nile valley.' },
    { emoji: '🐊', name: 'Nile crocodile', description: 'In Lake Nasser behind the Aswan dam (almost extinct downstream).', olderOnly: true },
    { emoji: '🦒', name: 'Hieroglyph animal', description: 'Spot any animal carved into a temple wall — cat, ibis, baboon, falcon, hippo.', olderOnly: true },
  ],
  turkey: [
    { emoji: '🐈', name: 'Istanbul street cat', description: 'Istanbul is famous for its cats. They have their own documentaries and food bowls everywhere.' },
    { emoji: '🐕', name: 'Friendly street dog', description: 'Tagged and vaccinated by the city. Big, calm, used to people.' },
    { emoji: '🕊️', name: 'Feral pigeon', description: 'New Mosque\'s courtyard in Eminönü is famous for the pigeon flocks.' },
    { emoji: '🦅', name: 'White stork', description: 'On rooftops along the Aegean coast and in Cappadocia, especially in spring.' },
    { emoji: '🐐', name: 'Angora goat', description: 'Long silky white hair — the source of mohair wool, from the Ankara region.', olderOnly: true },
    { emoji: '🐢', name: 'Loggerhead sea turtle', description: 'Nests on Iztuzu Beach in Dalyan — protected by guards every summer.', olderOnly: true },
  ],
  uae: [
    { emoji: '🐪', name: 'Dromedary camel', description: 'Beside every desert road and at the camel-race tracks. Robots ride them now (no more child jockeys).' },
    { emoji: '🦩', name: 'Greater flamingo', description: 'On the Ras Al Khor lagoon right next to Dubai. Pink flock against skyscrapers — surreal.' },
    { emoji: '🦎', name: 'Geckos and skinks', description: 'On every wall in the cooler hours. Tiny, fast, harmless.' },
    { emoji: '🐈', name: 'Arabian Mau', description: 'Short-haired street cat native to the Arabian Peninsula. Often spotted in old souks.' },
    { emoji: '🦅', name: 'Saker falcon', description: 'Falconry is the UAE national sport. Look in souks and at falcon hospitals.', olderOnly: true },
    { emoji: '🦌', name: 'Arabian oryx', description: 'Once extinct in the wild, reintroduced — white antelope with long straight horns in desert reserves.', olderOnly: true },
  ],
  india: [
    { emoji: '🐄', name: 'Sacred cow', description: 'Wandering free through cities, sleeping in the middle of roads. Drivers swerve around them.' },
    { emoji: '🐕', name: 'Indian Pariah dog', description: 'Tan-coloured street dog, the original ancient breed of South Asia.' },
    { emoji: '🐒', name: 'Rhesus macaque', description: 'On temple walls, ancient ruins, and outside Delhi metro stations. Watch your snacks.' },
    { emoji: '🐘', name: 'Asian elephant', description: 'In Kerala festivals, in Jaipur tourist parades, and wild in the parks of Karnataka and Kerala.' },
    { emoji: '🦚', name: 'Indian peafowl', description: 'India\'s national bird. Brilliant blue, displaying tail feathers in monsoon courtship dances.' },
    { emoji: '🐅', name: 'Bengal tiger', description: 'In Ranthambore, Bandhavgarh, Kanha. Real wild sightings are rare and unforgettable.', olderOnly: true },
    { emoji: '🐊', name: 'Mugger crocodile', description: 'On river banks in tiger reserves and the Chambal sanctuary.', olderOnly: true },
  ],
  china: [
    { emoji: '🕊️', name: 'Feral pigeon', description: 'In every city plaza and around every Buddhist temple.' },
    { emoji: '🐠', name: 'Koi carp', description: 'In ornamental ponds at temples, parks and traditional gardens.' },
    { emoji: '🐉', name: 'Chinese dragon', description: 'Not a real animal — but every temple roof, palace gate and festival has one. Spot the 5-claw imperial dragons.' },
    { emoji: '🦌', name: 'Sika deer', description: 'In northern China and Hokkaido-style parks. Sacred at some Buddhist sites.' },
    { emoji: '🐼', name: 'Giant panda', description: 'In Sichuan reserves like Chengdu and Wolong. Famously eats bamboo all day.', olderOnly: true },
    { emoji: '🦅', name: 'Red-crowned crane', description: 'Sacred long-legged bird, symbol of longevity. In Heilongjiang wetlands.', olderOnly: true },
  ],
  japan: [
    { emoji: '🐈', name: 'Cat-cafe cat', description: 'Japan loves cats. Cat cafés and "cat islands" (like Aoshima) exist for this reason.' },
    { emoji: '🦌', name: 'Sika deer of Nara', description: 'Around 1,000 freely-roaming sacred deer in Nara Park bow to you (then mug you for crackers).' },
    { emoji: '🐠', name: 'Koi carp', description: 'In every temple pond, garden pond and shrine pool. Some are 100+ years old.' },
    { emoji: '🐦', name: 'Common crane', description: 'On 1,000 yen notes and at Hokkaido marshes — the red-crowned crane is national symbol.' },
    { emoji: '🐒', name: 'Snow monkey (Japanese macaque)', description: 'In Nagano they bathe in hot springs in the snow. Adorable.', olderOnly: true },
    { emoji: '🐳', name: 'Humpback whale', description: 'On migration past Okinawa in winter and Hokkaido in summer.', olderOnly: true },
  ],
  vietnam: [
    { emoji: '🐃', name: 'Water buffalo', description: 'Ploughing rice paddies all over the country. Often ridden home by farm kids.' },
    { emoji: '🐕', name: 'Vietnamese street dog', description: 'The country has been working hard to end the dog-meat trade — most are pets now.' },
    { emoji: '🦎', name: 'Tokay gecko', description: 'Loud blue-grey-with-orange-spots gecko on house walls at night. Calls "to-kay! to-kay!".' },
    { emoji: '🐔', name: 'Free-range chicken', description: 'Crossing every village road. Will give you the side-eye.' },
    { emoji: '🐒', name: "Cat Ba langur", description: 'Critically endangered orange-yellow monkey, only on Cat Ba island in Halong Bay.', olderOnly: true },
    { emoji: '🦏', name: 'Saola', description: 'Asian "unicorn" antelope-like creature, only discovered in 1992. So rare you basically won\'t see one — but try.', olderOnly: true },
  ],
  cambodia: [
    { emoji: '🐃', name: 'Water buffalo', description: 'Working every rice paddy across the country, often led by a small kid with a stick.' },
    { emoji: '🐒', name: 'Long-tailed macaque', description: 'All over Angkor Wat. Curious, cheeky, will steal sunglasses.' },
    { emoji: '🦎', name: 'Tokay gecko', description: 'Big chunky gecko that lives in houses. Their loud call is the soundtrack of the night.' },
    { emoji: '🐘', name: 'Asian elephant', description: 'In the Mondulkiri sanctuary where rescued former working elephants now roam.' },
    { emoji: '🐬', name: 'Irrawaddy dolphin', description: 'Rare snub-nosed freshwater dolphins in the Mekong River near Kratie.', olderOnly: true },
    { emoji: '🦅', name: 'Giant ibis', description: 'Cambodia\'s national bird — only 200 left in the wild, mostly in the Northern Plains.', olderOnly: true },
  ],
  thailand: [
    { emoji: '🐘', name: 'Asian elephant', description: 'Thailand\'s national animal. At ethical sanctuaries (Elephant Nature Park) you can watch them roam, not ride them.' },
    { emoji: '🐈', name: 'Wat (temple) cat', description: 'Sleeping on cool tiles in every Buddhist temple courtyard.' },
    { emoji: '🐒', name: 'Long-tailed macaque', description: 'Lopburi town is overrun with them. Hold onto everything.' },
    { emoji: '🦎', name: 'Tokay gecko', description: 'Loud, common, found on every guesthouse wall after dark.' },
    { emoji: '🐅', name: 'Indochinese tiger', description: 'Almost extinct in the wild — fewer than 200 left, mostly in the Western Forest.', olderOnly: true },
    { emoji: '🐢', name: 'Hawksbill turtle', description: 'On the Andaman coast beaches, especially during November–March nesting season.', olderOnly: true },
  ],
  malaysia: [
    { emoji: '🐒', name: 'Long-tailed macaque', description: 'In every city park and every roadside stop. Will absolutely steal your lunch.' },
    { emoji: '🦎', name: 'House gecko', description: 'On every wall, in every shop. Tick-tick-tick at night.' },
    { emoji: '🦋', name: 'Rajah Brooke\'s birdwing', description: 'Huge black-and-iridescent-green butterfly of Borneo rainforests.' },
    { emoji: '🐢', name: 'Green sea turtle', description: 'Nests on Sabah\'s Turtle Islands. Lights-out beaches in nesting season.' },
    { emoji: '🦧', name: 'Bornean orangutan', description: 'In Sepilok sanctuary (Sabah) or the Kinabatangan river. Critically endangered.', olderOnly: true },
    { emoji: '🐗', name: 'Bearded pig', description: 'A wild pig native to Borneo, with bristly white whiskers. In Bako National Park.', olderOnly: true },
  ],
  indonesia: [
    { emoji: '🐒', name: 'Long-tailed macaque', description: 'In Ubud\'s Monkey Forest in Bali, in temples, and on roadsides everywhere.' },
    { emoji: '🦎', name: 'House gecko', description: 'On every wall, every ceiling, every restaurant. Their voice sounds like "geck-o".' },
    { emoji: '🐂', name: 'Bali cow (Banteng)', description: 'Working cattle ploughing Bali\'s rice paddies — descendants of the wild banteng.' },
    { emoji: '🐍', name: 'Reticulated python', description: 'The longest snake in the world lives here. (Usually only in rural areas, mostly hidden!)' },
    { emoji: '🐉', name: 'Komodo dragon', description: 'The world\'s biggest lizard — up to 3m long. Only on Komodo, Rinca and a few small islands.', olderOnly: true },
    { emoji: '🦧', name: 'Sumatran orangutan', description: 'Critically endangered, in Gunung Leuser National Park in northern Sumatra.', olderOnly: true },
  ],
  'sri-lanka': [
    { emoji: '🐘', name: 'Sri Lankan elephant', description: 'Around 6,000 still in the wild. Yala and Udawalawe parks are the best places.' },
    { emoji: '🐒', name: 'Toque macaque', description: 'Cheeky monkeys on every temple wall, with a comical "haircut" of fur on the head.' },
    { emoji: '🐅', name: 'Sri Lankan leopard', description: 'Yala National Park has one of the highest densities of leopards in the world.' },
    { emoji: '🦚', name: 'Indian peafowl', description: 'Bright iridescent blue, displaying tail-fans on Sigiriya rock or in dry-zone gardens.' },
    { emoji: '🐳', name: 'Blue whale', description: 'Off Mirissa and Trincomalee, you can see the biggest animal that has ever lived.', olderOnly: true },
    { emoji: '🐢', name: 'Hawksbill turtle', description: 'On the south and east coasts, especially around Rekawa and Kosgoda beaches.', olderOnly: true },
  ],
  nepal: [
    { emoji: '🐃', name: 'Water buffalo', description: 'Ploughing terraced fields in the hills and ferrying loads through villages.' },
    { emoji: '🐂', name: 'Sacred cow', description: 'Like in India, cows wander Kathmandu freely — never harmed.' },
    { emoji: '🐒', name: 'Rhesus macaque', description: 'Especially at the "Monkey Temple" (Swayambhunath) in Kathmandu.' },
    { emoji: '🦏', name: 'One-horned rhino', description: 'In Chitwan National Park — over 700 of them roam the grasslands and rivers.' },
    { emoji: '🐅', name: 'Bengal tiger', description: 'Chitwan has a healthy tiger population, but they\'re elusive — go on a multi-day safari to maximise chances.', olderOnly: true },
    { emoji: '🐆', name: 'Snow leopard', description: 'In the highest Himalayan valleys (Dolpo, Mustang). Almost no one sees one.', olderOnly: true },
  ],
  pakistan: [
    { emoji: '🐂', name: 'Working buffalo or zebu', description: 'Ploughing fields, pulling carts, providing milk for chai across Punjab and Sindh.' },
    { emoji: '🦅', name: 'Black kite', description: 'Forked-tail bird of prey circling above every Pakistani city, especially Karachi and Lahore.' },
    { emoji: '🐈', name: 'Bazaar cat', description: 'Sleek street cats in every old-city market, fed by spice traders.' },
    { emoji: '🦌', name: 'Markhor', description: 'Pakistan\'s national animal — a wild goat with massive corkscrew horns. In Chitral and Hunza.' },
    { emoji: '🐆', name: 'Snow leopard', description: 'In the high Karakoram — fewer than 250 in the country. Spotted by very few people.', olderOnly: true },
    { emoji: '🐬', name: 'Indus river dolphin', description: 'A blind freshwater dolphin found only in the Indus. Critically endangered.', olderOnly: true },
  ],
  bangladesh: [
    { emoji: '🐂', name: 'Working zebu cow', description: 'Pulling carts and ploughs across the rural delta.' },
    { emoji: '🦅', name: 'Brahminy kite', description: 'Reddish-brown raptor with a white head, soaring above the rivers.' },
    { emoji: '🐈', name: 'Bazaar cat', description: 'Slim short-haired street cats in every Dhaka old-city market.' },
    { emoji: '🐊', name: 'Saltwater crocodile', description: 'In the Sundarbans tidal rivers. The biggest reptile on Earth.' },
    { emoji: '🐅', name: 'Royal Bengal tiger', description: 'Around 100 in the Sundarbans — strong swimmers, hunting in the mangroves.', olderOnly: true },
    { emoji: '🐬', name: 'Ganges river dolphin', description: 'A blind freshwater dolphin in the Sundarbans and main delta rivers.', olderOnly: true },
  ],
  laos: [
    { emoji: '🐃', name: 'Water buffalo', description: 'Ploughing every rice paddy in the country. Often watched over by a small kid.' },
    { emoji: '🐕', name: 'Lao village dog', description: 'Calm, sun-baked, ear-flopping dogs around every temple gate and market.' },
    { emoji: '🦎', name: 'Tokay gecko', description: 'Loud "to-kay! to-kay!" call from house walls at night.' },
    { emoji: '🐂', name: 'Free-range cow', description: 'Wandering along country roads — drivers stop and wait.' },
    { emoji: '🐘', name: 'Asian elephant', description: 'At the Elephant Conservation Center in Sayaboury, where retired logging elephants live.', olderOnly: true },
    { emoji: '🐬', name: 'Irrawaddy dolphin', description: 'Around the 4,000 Islands in the south, on the Mekong near the Cambodian border.', olderOnly: true },
  ],

  // ── AFRICA ──────────────────────────────────────────────────────
  'south-africa': [
    { emoji: '🦓', name: 'Plains zebra', description: 'Black-and-white striped zebra in Kruger and most South African game parks.' },
    { emoji: '🦒', name: 'Giraffe', description: 'Easy to spot above the bush in Kruger and many private reserves.' },
    { emoji: '🐘', name: 'African elephant', description: 'Kruger has around 30,000. Often crossing the road in front of your car.' },
    { emoji: '🦁', name: 'Lion', description: 'Best at dawn or dusk in Kruger, the Kalahari, or any of the big reserves.' },
    { emoji: '🐧', name: 'African penguin', description: 'Boulders Beach near Cape Town. The only "jackass" penguins in Africa.' },
    { emoji: '🦏', name: 'Rhino', description: 'Black or white rhino in Kruger and the Hluhluwe reserves. Guarded around the clock from poachers.', olderOnly: true },
    { emoji: '🐆', name: 'Leopard', description: 'Elusive but Sabi Sand has the highest sighting success in Africa.', olderOnly: true },
  ],
  kenya: [
    { emoji: '🦁', name: 'Lion', description: 'Best at dawn and dusk in the Maasai Mara. Whole prides relaxing in the open grass.' },
    { emoji: '🐘', name: 'African elephant', description: 'Amboseli has huge herds with Mount Kilimanjaro behind them. Tsavo herds get the famous red colour from rolling in the dust.' },
    { emoji: '🦓', name: 'Plains zebra', description: 'In huge herds in the Mara, often mixed with wildebeest during the Great Migration.' },
    { emoji: '🦒', name: 'Maasai giraffe', description: 'The biggest giraffe species, with jagged-edged spots. Common in the Mara and Amboseli.' },
    { emoji: '🦅', name: 'Fish eagle', description: 'The famous call of African rivers and Rift Valley lakes. Often seen perched over Lake Naivasha.' },
    { emoji: '🦏', name: 'Black rhino', description: 'Critically endangered. Best sightings now in conservancies like Ol Pejeta on the slopes of Mount Kenya.', olderOnly: true },
    { emoji: '🐆', name: 'Cheetah', description: 'The Mara open plains are one of the best places in Africa to watch a cheetah hunt.', olderOnly: true },
  ],
  nigeria: [
    { emoji: '🐒', name: 'Mona monkey', description: 'Common in southern forests and even some Lagos parks. Olive-brown with a long tail.' },
    { emoji: '🦜', name: 'Senegal parrot', description: 'Bright green and yellow, often kept as a pet but also seen flying wild across the savanna.' },
    { emoji: '🐊', name: 'Nile crocodile', description: 'In the rivers and lagoons of the Niger Delta and the inland rivers.' },
    { emoji: '🐃', name: 'African buffalo', description: 'In Cross River and Yankari national parks. Heavy, dangerous, usually in herds.' },
    { emoji: '🦛', name: 'Hippo', description: 'In the Niger River and the rivers of Cross River state. Dangerous, give them space.' },
    { emoji: '🐘', name: 'Forest elephant', description: 'Smaller than savanna elephants and very rare. The last refuge is the Cross River rainforest.', olderOnly: true },
    { emoji: '🦍', name: 'Cross River gorilla', description: 'The rarest gorilla on Earth, fewer than 300 left, only in the Nigerian-Cameroonian border forests.', olderOnly: true },
  ],
  ghana: [
    { emoji: '🐐', name: 'West African dwarf goat', description: 'Everywhere in every village, on the road, eating roadside weeds.' },
    { emoji: '🐒', name: 'Mona monkey', description: 'In the sacred Boabeng-Fiema Monkey Sanctuary, where the monkeys are protected by local belief.' },
    { emoji: '🦋', name: 'Tropical butterflies', description: 'Kakum National Park is famous for hundreds of butterfly species, biggest as a small bird.' },
    { emoji: '🐊', name: 'Crocodile', description: 'At Paga in the far north, you can sit next to friendly sacred crocs in the village pond.' },
    { emoji: '🐘', name: 'African elephant', description: 'In Mole National Park you can walk with the elephants on foot, the only park in West Africa that lets you.' },
    { emoji: '🦒', name: 'Kob antelope', description: 'A pale honey-coloured antelope common in Mole, often in herds.', olderOnly: true },
    { emoji: '🦌', name: 'Bushbuck', description: 'Shy reddish-brown forest antelope, especially in Kakum.', olderOnly: true },
  ],
  malawi: [
    { emoji: '🐟', name: 'Lake Malawi cichlid', description: 'Brightly coloured small fish, with over 1,000 species in this one lake. Snorkel along the rocky shores to see them.' },
    { emoji: '🦅', name: 'African fish eagle', description: 'The national bird of Malawi. Its loud yelping call is the sound of the lake.' },
    { emoji: '🦛', name: 'Hippopotamus', description: 'In Liwonde National Park along the Shire River, often dozens visible from the riverbank at dusk.' },
    { emoji: '🐘', name: 'African elephant', description: 'Liwonde and Majete national parks both have growing herds.' },
    { emoji: '🐊', name: 'Nile crocodile', description: 'In the Shire River and along Lake Malawi shores. Always check with locals before swimming.' },
    { emoji: '🦓', name: 'Plains zebra', description: 'On the Nyika Plateau and in Majete, often grazing alongside antelopes.', olderOnly: true },
    { emoji: '🐆', name: 'Leopard', description: 'Returning to Liwonde and Majete after years of being almost wiped out. Hard to spot but worth trying.', olderOnly: true },
  ],
  algeria: [
    { emoji: '🦊', name: 'Fennec fox', description: 'Algeria\'s national animal. Tiny desert fox with enormous bat-like ears, found in the Sahara.' },
    { emoji: '🐪', name: 'Dromedary camel', description: 'The single-hump desert camel. Tuareg families still use them as transport and as a source of milk and meat.' },
    { emoji: '🐐', name: 'Berber goat', description: 'In every Algerian mountain village, kept for milk and meat.' },
    { emoji: '🐎', name: 'Berber horse', description: 'An ancient North African breed, sturdy and small, used by Berber riders for thousands of years.' },
    { emoji: '🦅', name: 'Bonelli\'s eagle', description: 'A medium-sized eagle of the Algerian mountains and Saharan cliffs.' },
    { emoji: '🐆', name: 'Sand cat', description: 'A small wild cat that lives only in deserts. Sandy-coloured, very hard to spot.', olderOnly: true },
    { emoji: '🐎', name: 'Barbary macaque', description: 'The only monkey native to North Africa, in the cedar forests of northern Algeria and Morocco.', olderOnly: true },
  ],
  tunisia: [
    { emoji: '🐈', name: 'Medina cat', description: 'Cats lounging in plant pots, on warm blue tiles, in every Sidi Bou Said and Tunis doorway.' },
    { emoji: '🦊', name: 'Fennec fox', description: 'The same big-eared desert fox as in Algeria. In the southern Tunisian Sahara.' },
    { emoji: '🐪', name: 'Dromedary camel', description: 'In the south, used for tourist rides into the dunes and for working in the oases.' },
    { emoji: '🦩', name: 'Greater flamingo', description: 'Big flocks at the salt lakes of Ichkeul and the lagoons near Djerba.' },
    { emoji: '🦅', name: 'White stork', description: 'Storks nest on the tops of minarets and ruined Roman columns across the north.' },
    { emoji: '🦌', name: 'Barbary deer', description: 'A small reddish deer found in the cork-oak forests of the far north. Endangered.', olderOnly: true },
    { emoji: '🦦', name: 'Eurasian otter', description: 'Returning to the lakes and rivers of the Tunisian Atlas mountains.', olderOnly: true },
  ],
  zimbabwe: [
    { emoji: '🐘', name: 'African elephant', description: 'Hwange has one of the biggest elephant populations on the continent, sometimes 50,000+ in dry season around the pumped waterholes.' },
    { emoji: '🦛', name: 'Hippopotamus', description: 'In huge pods along the Zambezi River above and below Victoria Falls.' },
    { emoji: '🦅', name: 'African fish eagle', description: 'Its piercing call echoes across the Zambezi and Lake Kariba. The "sound of Africa".' },
    { emoji: '🦓', name: 'Plains zebra', description: 'Across all the parks. Sometimes mixed with eland (the biggest antelope on Earth).' },
    { emoji: '🐗', name: 'Warthog', description: 'Trotting across savanna roads with their tails straight up. Especially common in Hwange.' },
    { emoji: '🦏', name: 'Black rhino', description: 'Matobo National Park is one of the best places in Africa to track black rhino on foot.', olderOnly: true },
    { emoji: '🐆', name: 'Leopard', description: 'On granite kopjes at dawn in Matobo, or up an acacia tree in Hwange.', olderOnly: true },
  ],
  tanzania: [
    { emoji: '🦁', name: 'Lion', description: 'The Serengeti has the largest lion population on Earth. Whole prides on rocky kopjes at dawn.' },
    { emoji: '🐘', name: 'African elephant', description: 'Huge herds in Tarangire National Park, especially in the dry season around the baobabs.' },
    { emoji: '🦓', name: 'Plains zebra', description: 'In huge mixed herds with wildebeest during the Great Migration through the Serengeti.' },
    { emoji: '🦒', name: 'Maasai giraffe', description: 'The national animal of Tanzania, browsing acacia trees on the savanna.' },
    { emoji: '🦛', name: 'Hippopotamus', description: 'Crowded pools in the Serengeti and Selous, snorting and yawning at dusk.' },
    { emoji: '🦏', name: 'Black rhino', description: 'Critically endangered. Ngorongoro Crater holds one of the last viable Tanzanian populations.', olderOnly: true },
    { emoji: '🐒', name: 'Chimpanzee', description: 'In the Mahale and Gombe forests on the shores of Lake Tanganyika. Jane Goodall studied them here.', olderOnly: true },
  ],
  jordan: [
    { emoji: '🐪', name: 'Dromedary camel', description: 'In Wadi Rum and across the southern desert. Bedouin families still rely on them.' },
    { emoji: '🐐', name: 'Bedouin goat', description: 'In every nomadic camp, kept for milk, meat and wool.' },
    { emoji: '🐎', name: 'Arabian horse', description: 'Bred for thousands of years in the deserts of Jordan and Arabia. Famous for their endurance.' },
    { emoji: '🦅', name: 'Steppe eagle', description: 'Migrating in big flocks across Jordan twice a year, between Africa and central Asia.' },
    { emoji: '🦂', name: 'Yellow scorpion', description: 'Common in the desert at night. Best admired with a torch and a respectful distance.' },
    { emoji: '🐠', name: 'Lionfish', description: 'In the Red Sea coral reefs off Aqaba. Striped and spiky, beautiful from a snorkel.', olderOnly: true },
    { emoji: '🦌', name: 'Nubian ibex', description: 'A wild mountain goat with huge curved horns, living on the cliffs around the Dead Sea.', olderOnly: true },
  ],
  'south-korea': [
    { emoji: '🐈', name: 'Korean street cat', description: 'In Seoul alleys, Jeju villages and temple grounds. Often fed by neighbours.' },
    { emoji: '🐕', name: 'Jindo dog', description: 'A native Korean breed, famously loyal. Named after Jindo Island where they come from.' },
    { emoji: '🦌', name: 'Sika deer', description: 'In Seoraksan National Park. The fawns are spotted; the bucks have branching antlers.' },
    { emoji: '🦅', name: 'Black kite', description: 'Soaring over Seoul rivers and coastal cliffs.' },
    { emoji: '🐦', name: 'Magpie', description: 'Black-and-white birds with iridescent blue wings. The unofficial national bird.' },
    { emoji: '🐅', name: 'Amur leopard', description: 'Critically endangered, fewer than 100 left in the wild on the Korea-Russia-China border.', olderOnly: true },
    { emoji: '🐋', name: 'Minke whale', description: 'Off the east coast of Korea, especially around Ulsan and the Sea of Japan.', olderOnly: true },
  ],
  singapore: [
    { emoji: '🦦', name: 'Smooth-coated otter', description: 'Wild otter families have moved back into central Singapore canals and the Marina Bay area. Beloved local celebrities.' },
    { emoji: '🦎', name: 'Asian water monitor', description: 'Big black lizards up to 2 m long, swimming in canals and crossing park paths. Harmless to humans.' },
    { emoji: '🐒', name: 'Long-tailed macaque', description: 'In the Bukit Timah forest and MacRitchie reservoir. Keep your snacks zipped up.' },
    { emoji: '🦋', name: 'Tropical butterflies', description: 'Hundreds of species in the Botanic Gardens and at the Changi Airport butterfly garden.' },
    { emoji: '🦜', name: 'Hornbill', description: 'Big black birds with bright bills, returning to Singapore parks after decades of absence.' },
    { emoji: '🐠', name: 'Coral reef fish', description: 'Around the small Singapore Southern Islands (Sisters\' Islands, Pulau Hantu).', olderOnly: true },
    { emoji: '🐍', name: 'Reticulated python', description: 'The world\'s longest snake species lives wild in Singapore parks. Spotted but rarely; harmless if left alone.', olderOnly: true },
  ],
  czechia: [
    { emoji: '🦌', name: 'Red deer', description: 'In the Šumava forest and Bohemian Switzerland. The biggest deer in Europe.' },
    { emoji: '🐗', name: 'Wild boar', description: 'Across the Czech countryside, especially in autumn. Occasionally wandering into the outskirts of Prague.' },
    { emoji: '🦫', name: 'European beaver', description: 'Returned to Czech rivers after almost going extinct. Look for chewed willow stumps along the Vltava.' },
    { emoji: '🦅', name: 'White-tailed eagle', description: 'Czechia\'s biggest eagle, with a 2.5 m wingspan. Around lakes in southern Bohemia.' },
    { emoji: '🐕', name: 'Working farm dog', description: 'Often a Czech wolfdog or a Bohemian shepherd, on small countryside farms.' },
    { emoji: '🐻', name: 'Brown bear', description: 'Returning slowly to the Beskydy mountains on the Slovakian border.', olderOnly: true },
    { emoji: '🐱', name: 'Eurasian lynx', description: 'About 100 lynx live in Czech forests, mostly in the Šumava and Beskydy ranges. Almost impossible to spot.', olderOnly: true },
  ],
  cuba: [
    { emoji: '🐦', name: 'Cuban tody', description: 'A tiny bright-green bird with a pink belly. Endemic to Cuba (found nowhere else). About 11 cm long.' },
    { emoji: '🦎', name: 'Cuban rock iguana', description: 'On the cays and small islands off Cuba. Up to 1.5 m long, slow and harmless.' },
    { emoji: '🦀', name: 'Land crab', description: 'In spring, millions of red land crabs migrate from the forest to the sea to lay eggs, especially around the Bay of Pigs.' },
    { emoji: '🐊', name: 'Cuban crocodile', description: 'A small, agile crocodile species found only in Cuba\'s Zapata swamp. Critically endangered.', olderOnly: true },
    { emoji: '🐬', name: 'Atlantic spotted dolphin', description: 'Off Cuba\'s north coast, often playing in the bow waves of boats.', olderOnly: true },
    { emoji: '🦩', name: 'Caribbean flamingo', description: 'Big pink flocks in the Cayo Coco salt lagoons on the north coast.', olderOnly: true },
    { emoji: '🐦', name: 'Bee hummingbird', description: 'The smallest bird on Earth, only 5 cm long. Found only in Cuba.' },
  ],
  bolivia: [
    { emoji: '🦙', name: 'Llama', description: 'Across the altiplano, used for carrying loads and for wool. Sometimes wearing colourful ear tassels.' },
    { emoji: '🦙', name: 'Alpaca', description: 'Fluffier than a llama, with much softer fleece. In the highest highland pastures.' },
    { emoji: '🦅', name: 'Andean condor', description: 'One of the world\'s biggest flying birds (3 m wingspan), soaring above the Andean peaks.' },
    { emoji: '🦩', name: 'Andean / James\'s / Chilean flamingo', description: 'Bolivia is one of the few places where all THREE South American flamingo species live, at the high salt lakes near Uyuni.' },
    { emoji: '🦙', name: 'Vicuña', description: 'The wild ancestor of the alpaca, with the finest wool in the world. Protected on the altiplano.' },
    { emoji: '🦥', name: 'Pink river dolphin', description: 'In the Bolivian Amazon (the Pampas) around Rurrenabaque.', olderOnly: true },
    { emoji: '🐆', name: 'Jaguar', description: 'In the Madidi National Park rainforests, although extremely hard to spot.', olderOnly: true },
  ],
  namibia: [
    { emoji: '🦓', name: 'Hartmann\'s mountain zebra', description: 'A desert-adapted zebra with very narrow stripes. Climbs steep dry hills around Damaraland.' },
    { emoji: '🦒', name: 'Giraffe', description: 'Across Etosha and Damaraland. Sometimes drinking awkwardly with legs splayed.' },
    { emoji: '🐘', name: 'Desert elephant', description: 'Specially adapted elephants that walk dry riverbeds in Damaraland and Kaokoland. Smaller feet, longer legs than savanna elephants.' },
    { emoji: '🦁', name: 'Lion', description: 'In Etosha. The desert-adapted lions of the Skeleton Coast region survive on shipwrecked seals and antelope.' },
    { emoji: '🦏', name: 'Black rhino', description: 'Namibia has the largest free-ranging black rhino population on Earth, in Etosha and protected community conservancies.' },
    { emoji: '🦅', name: 'Lappet-faced vulture', description: 'Africa\'s biggest vulture, with a 3 m wingspan. Soaring above Etosha.', olderOnly: true },
    { emoji: '🐆', name: 'Cheetah', description: 'Namibia holds the largest wild cheetah population in the world. Best at Cheetah Conservation Fund near Otjiwarongo.', olderOnly: true },
  ],
  botswana: [
    { emoji: '🐘', name: 'African elephant', description: 'Chobe National Park has the highest density of African elephants on Earth (around 130,000 in the country).' },
    { emoji: '🦛', name: 'Hippopotamus', description: 'Big pods in the Okavango Delta channels, often grunting near mokoro routes.' },
    { emoji: '🦁', name: 'Lion', description: 'Across the delta and Kalahari. The Okavango lions have learned to swim and hunt buffalo through the floods.' },
    { emoji: '🐃', name: 'African buffalo', description: 'Big dark herds in Chobe and the Okavango. Heavy, dangerous, always in groups.' },
    { emoji: '🦓', name: 'Plains zebra', description: 'Botswana hosts one of Africa\'s longest zebra migrations, between the Okavango and the Makgadikgadi pans.' },
    { emoji: '🐕', name: 'African wild dog', description: 'Botswana has Africa\'s biggest wild-dog population. Painted with brown, black, white and yellow patches. Endangered.', olderOnly: true },
    { emoji: '🐆', name: 'Leopard', description: 'In the riverine forests of the Okavango, often draped on the branch of a sausage-tree at sunset.', olderOnly: true },
  ],
  fiji: [
    { emoji: '🐠', name: 'Coral reef fish', description: 'Hundreds of species around the Mamanuca and Yasawa islands. Bright butterflyfish, parrotfish, sergeant majors.' },
    { emoji: '🐢', name: 'Green sea turtle', description: 'Glide through the reefs and rest on shallow sandbanks. Protected and rebounding well.' },
    { emoji: '🦈', name: 'Blacktip reef shark', description: 'Common on shallow reefs, usually harmless to people. Distinctive black-tipped dorsal fin breaking the surface.' },
    { emoji: '🐦', name: 'Collared lory', description: 'A bright red-and-green parrot found only in Fiji.' },
    { emoji: '🦀', name: 'Coconut crab', description: 'The biggest land arthropod on Earth (up to 9 lbs). Climbs coconut trees to drop them. Mostly seen at night.' },
    { emoji: '🐠', name: 'Mantis shrimp', description: 'A small reef shrimp that punches with the speed of a bullet. Among the fastest movements in the animal kingdom.', olderOnly: true },
    { emoji: '🐳', name: 'Humpback whale', description: 'Migrates through Fijian waters July to October, breaching and tail-slapping near the islands.', olderOnly: true },
  ],
  philippines: [
    { emoji: '🐃', name: 'Carabao (water buffalo)', description: 'The national animal. Big, slow, and used for ploughing rice paddies across the country.' },
    { emoji: '🦦', name: 'Philippine tarsier', description: 'Tiny nocturnal primate with HUGE eyes. Lives in Bohol\'s rainforest. Only as big as your fist.' },
    { emoji: '🦅', name: 'Philippine eagle', description: 'The national bird, one of the largest and rarest eagles on Earth. Lives only on Mindanao. Critically endangered.' },
    { emoji: '🐠', name: 'Clownfish', description: 'In coral reefs in Anilao, Apo Island, Bohol. Made famous by Finding Nemo, still everywhere on Philippine reefs.' },
    { emoji: '🦋', name: 'Whale shark (butanding)', description: 'The biggest fish on Earth, gentle plankton-eater. Swimming with them at Donsol or Oslob is one of Asia\'s great wildlife encounters.' },
    { emoji: '🐊', name: 'Saltwater crocodile', description: 'In the Agusan Marsh, Mindanao. Rare in the Philippines but the world\'s largest reptile species.', olderOnly: true },
    { emoji: '🦋', name: 'Mindanao bleeding-heart pigeon', description: 'A ground-dwelling pigeon with a red splash of feathers on its chest that looks like a bleeding heart. Endangered, found only in the Philippines.', olderOnly: true },
  ],
  taiwan: [
    { emoji: '🐈', name: 'Houtong cat village cats', description: 'A whole train-station village near Taipei (Houtong) has become a cat-lovers\' paradise, with dozens of friendly cats lounging everywhere.' },
    { emoji: '🐦', name: 'Mikado pheasant', description: 'A dark blue and shy mountain pheasant found only in Taiwan, on the back of the 1,000 NT$ bill.' },
    { emoji: '🦋', name: 'Tropical butterflies', description: 'Taiwan has 400+ butterfly species. The Maolin Purple Butterfly Valley hosts the world\'s second-largest butterfly migration in winter.' },
    { emoji: '🐒', name: 'Formosan rock macaque', description: 'A small native macaque living wild in Taiwan\'s mountain parks. Found only here.' },
    { emoji: '🐦', name: 'Black-faced spoonbill', description: 'A long-billed wader that winters in big flocks on Taiwan\'s south-west coast wetlands. Globally endangered.' },
    { emoji: '🐻', name: 'Formosan black bear', description: 'Taiwan\'s only native bear, with a distinctive white V on its chest. Endangered, lives in the mountains.', olderOnly: true },
    { emoji: '🐬', name: 'Spinner dolphin', description: 'Plays in pods off the east coast of Taiwan, especially Hualien.', olderOnly: true },
  ],
  slovenia: [
    { emoji: '🐻', name: 'Brown bear', description: 'Slovenia has one of the largest brown bear populations in Europe (about 1,000 bears, mostly in the south).' },
    { emoji: '🐺', name: 'Grey wolf', description: 'Returning to the Slovenian forests after near-extinction in the 20th century. Mostly in the Notranjska region.' },
    { emoji: '🐱', name: 'Eurasian lynx', description: 'About 100 lynx live in Slovenian forests, especially the Kočevski Rog. Hard to see but their tracks turn up in winter snow.' },
    { emoji: '🐎', name: 'Lipizzaner horse', description: 'The white show-horse breed originally from the Slovenian village of Lipica, dating back to 1580. Still bred at the Lipica Stud Farm today.' },
    { emoji: '🐝', name: 'Carniolan honeybee', description: 'A particularly gentle native bee. Slovenia is one of the most beekeeping-mad countries on Earth.' },
    { emoji: '🦎', name: 'Olm (proteus)', description: 'The "human fish": a pale, eyeless, finger-sized cave salamander that lives only in Slovenian and Balkan cave waters. Can live 100+ years.', olderOnly: true },
    { emoji: '🦅', name: 'Golden eagle', description: 'Nests in the Julian Alps and Triglav National Park. About 70 pairs in the country.', olderOnly: true },
  ],
  maldives: [
    { emoji: '🐢', name: 'Green sea turtle', description: 'Glides over coral reefs across the country. Often seen on snorkels and dives.' },
    { emoji: '🐠', name: 'Clownfish', description: 'Bright orange-and-white reef fish hiding in sea anemones across the country.' },
    { emoji: '🦈', name: 'Whitetip reef shark', description: 'Common on reefs, mostly harmless, with a distinctive white-tipped dorsal fin.' },
    { emoji: '🐡', name: 'Manta ray', description: 'Huge graceful filter-feeders gathering at Hanifaru Bay, Baa Atoll (May to November).' },
    { emoji: '🐳', name: 'Whale shark', description: 'The biggest fish on Earth. Snorkel alongside one off South Ari Atoll (year-round) or Hanifaru in monsoon season.' },
    { emoji: '🐙', name: 'Reef octopus', description: 'Often spotted at dawn or dusk on reefs, changing colour as it slips between coral heads.', olderOnly: true },
    { emoji: '🦋', name: 'Flying fox (Indian flying fox)', description: 'The biggest bat species in the world lives in the Maldives. Wingspans up to 1.5 m. Often seen at dusk.', olderOnly: true },
  ],
  bhutan: [
    { emoji: '🐃', name: 'Yak', description: 'Long-haired highland cattle, kept by Bhutanese nomadic families for milk, cheese and wool. Above 3,000 m.' },
    { emoji: '🐎', name: 'Takin', description: 'Bhutan\'s national animal. Looks like a cross between a goat and a moose, with a curving nose. Found in alpine meadows.' },
    { emoji: '🐦', name: 'Black-necked crane', description: 'A rare crane that winters in Bhutan\'s Phobjikha Valley (October to February). The Bhutanese people consider them sacred.' },
    { emoji: '🦅', name: 'Himalayan vulture', description: 'A massive scavenger with a 3 m wingspan, gliding above the high passes.' },
    { emoji: '🐕', name: 'Bhutanese street dog', description: 'Friendly, well-fed dogs everywhere in Bhutanese towns. Buddhism teaches kindness to all living things.' },
    { emoji: '🦌', name: 'Red panda', description: 'A small fluffy rust-coloured tree-climber in Bhutan\'s east. Wild population is very small.', olderOnly: true },
    { emoji: '🐅', name: 'Bengal tiger', description: 'Bhutan has the highest-altitude tigers on Earth, found at over 4,000 m. Extremely rare to see.', olderOnly: true },
  ],
  guatemala: [
    { emoji: '🦜', name: 'Resplendent quetzal', description: 'Guatemala\'s national bird. Brilliant emerald green and red, with a tail twice as long as its body. In the cloud forests.' },
    { emoji: '🦜', name: 'Scarlet macaw', description: 'Bright red, yellow and blue parrot in the lowland jungles around Tikal.' },
    { emoji: '🐒', name: 'Howler monkey', description: 'The loudest land animal on Earth. Their dawn roars can be heard for kilometres through the Tikal rainforest.' },
    { emoji: '🦋', name: 'Blue morpho butterfly', description: 'Electric-blue wings as big as your hand, fluttering through the rainforest.' },
    { emoji: '🐍', name: 'Boa constrictor', description: 'Large non-venomous snake of the lowland jungles. Harmless to humans unless trodden on.' },
    { emoji: '🐆', name: 'Jaguar', description: 'Lives in Guatemala\'s northern Petén rainforest. Almost impossible to spot, but their tracks turn up in mud.', olderOnly: true },
    { emoji: '🦗', name: 'Leaf-cutter ant', description: 'Long lines of ants carrying cut bits of leaf many times their size, in every Mayan ruin and rainforest path.', olderOnly: true },
  ],
  belize: [
    { emoji: '🐢', name: 'Green sea turtle', description: 'Common on the Belize Barrier Reef and in seagrass beds. The Hol Chan Marine Reserve protects them.' },
    { emoji: '🦈', name: 'Nurse shark', description: 'Slow, harmless reef sharks. Often resting under coral ledges. Shark Ray Alley in Caye Caulker is famous for them.' },
    { emoji: '🦭', name: 'West Indian manatee', description: 'Slow, gentle sea mammals in the lagoons around Placencia. Look for them grazing on seagrass.' },
    { emoji: '🦜', name: 'Keel-billed toucan', description: 'The Belize national bird. Massive rainbow beak almost as long as its body.' },
    { emoji: '🐆', name: 'Jaguar', description: 'Belize has Central America\'s biggest jaguar population. Cockscomb Basin is the only nature reserve in the world set up specifically to protect them.' },
    { emoji: '🐊', name: 'Morelet\'s crocodile', description: 'A smaller, shy freshwater crocodile, in Belize\'s rivers. Different from the saltwater kind, much less dangerous.', olderOnly: true },
    { emoji: '🐍', name: 'Fer-de-lance', description: 'A venomous pit-viper of the rainforest. Always watch your step on jungle trails.', olderOnly: true },
  ],
  antarctica: [
    { emoji: '🐧', name: 'Emperor penguin', description: 'The biggest penguin (up to 1.3 m tall). Breeds in the dead of Antarctic winter on the open sea ice. Males balance the egg on their feet for two months.' },
    { emoji: '🐧', name: 'Adélie penguin', description: 'A small black-and-white penguin (50 cm), often seen waddling in big colonies on rocky coasts.' },
    { emoji: '🐳', name: 'Humpback whale', description: 'The most-seen whale on Antarctic cruises. Feeds on krill, breaches near boats, sometimes "spy hops" to look at you.' },
    { emoji: '🦭', name: 'Leopard seal', description: 'A long, powerful, spotted seal. The main predator of Adélie penguins. Will sometimes lift its head out of the water and stare you down from an ice floe.' },
    { emoji: '🦭', name: 'Crabeater seal', description: 'Despite the name, eats krill (not crabs). The most common seal on Earth, with around 15 million in Antarctic waters.' },
    { emoji: '🐦', name: 'Wandering albatross', description: 'Has the largest wingspan of any living bird (up to 3.5 m). Glides for thousands of kilometres without flapping.', olderOnly: true },
    { emoji: '🐳', name: 'Orca (killer whale)', description: 'Big black-and-white dolphins that hunt seals and penguins in coordinated pods. Several Antarctic orca pods specialise in different hunting strategies.', olderOnly: true },
  ],
  greenland: [
    { emoji: '🐕', name: 'Greenland sled dog', description: 'One of the oldest dog breeds on Earth. Strong, fluffy, built for cold. About 15,000 still working in northern Greenland today.' },
    { emoji: '🦭', name: 'Ringed seal', description: 'The smallest Arctic seal, with distinctive ring-shaped markings. The main food of polar bears.' },
    { emoji: '🐋', name: 'Humpback whale', description: 'Common in Greenland\'s coastal waters in summer, especially around Disko Bay.' },
    { emoji: '🦌', name: 'Reindeer (caribou)', description: 'Big herds of reindeer roam Greenland\'s west coast. Hunted traditionally by Inuit families for meat and hides.' },
    { emoji: '🐦', name: 'Arctic tern', description: 'A small, fierce seabird that holds the world record for animal migration: from the Arctic to Antarctica and back, every year, around 70,000 km.' },
    { emoji: '🐻‍❄️', name: 'Polar bear', description: 'Found in the far north and east of Greenland. The largest land predator on Earth. Dangerous, kept at distance.', olderOnly: true },
    { emoji: '🐄', name: 'Musk ox', description: 'Prehistoric-looking shaggy beasts living in west and north-east Greenland. Survived the last ice age.', olderOnly: true },
  ],
  'hong-kong': [
    { emoji: '🐦', name: 'Black kite', description: 'Big brown birds of prey soaring above Victoria Harbour and the city, often spotted from rooftops and ferries.' },
    { emoji: '🦋', name: 'Common Mormon butterfly', description: 'Big black-and-white butterflies common in the Hong Kong Park and country parks.' },
    { emoji: '🦎', name: 'Tokay gecko', description: 'Big tropical geckos in older buildings and country-park trees. Famous loud "to-kay! to-kay!" call.' },
    { emoji: '🐬', name: 'Chinese white dolphin (pink dolphin)', description: 'A pale-pink dolphin native to the Pearl River estuary near Lantau. Endangered, with maybe 50 left in Hong Kong waters.' },
    { emoji: '🐂', name: 'Wild ox', description: 'Feral cattle wander Lantau\'s south coast (Pui O), descendants of farm cows abandoned decades ago.' },
    { emoji: '🦅', name: 'Crested goshawk', description: 'A bird of prey that has adapted to Hong Kong\'s urban parks, sometimes nesting on apartment blocks.', olderOnly: true },
    { emoji: '🐊', name: 'Saltwater crocodile', description: 'In 2003 a saltwater crocodile turned up in a Hong Kong river and stayed for 5 years before being caught. "Pui Pui" is now an unofficial city legend.', olderOnly: true },
  ],
  croatia: [
    { emoji: '🐻', name: 'Brown bear', description: 'About 1,000 brown bears live in Croatia, mostly in the Gorski Kotar forests. Hard to see in the wild.' },
    { emoji: '🐺', name: 'Grey wolf', description: 'Returned to Croatian forests after near-extinction. A few hundred live in the mountains.' },
    { emoji: '🐬', name: 'Bottlenose dolphin', description: 'In the Adriatic around Lošinj, the only resident dolphin population in the Croatian Adriatic. Protected.' },
    { emoji: '🦋', name: 'Mediterranean butterflies', description: 'Hundreds of species across the Croatian coast and islands, especially in the limestone hills above Dubrovnik.' },
    { emoji: '🐈', name: 'Kotor cat', description: 'Cats roam the cobbled streets and city walls of Croatian Adriatic towns, especially Hvar and Dubrovnik. Practically national mascots.' },
    { emoji: '🐢', name: 'Loggerhead sea turtle', description: 'Rare sightings in the southern Croatian Adriatic, mostly around Mljet and the Lastovo archipelago.', olderOnly: true },
    { emoji: '🦅', name: 'Griffon vulture', description: 'A huge vulture with a 2.8 m wingspan, nesting on the cliffs of Cres island in the northern Adriatic.', olderOnly: true },
  ],
  albania: [
    { emoji: '🦅', name: 'Golden eagle', description: 'The national bird, on the flag and the country\'s self-name ("Shqipëria" means "Land of Eagles"). Lives in the Albanian Alps.' },
    { emoji: '🐐', name: 'Mountain goat', description: 'In the rugged northern Accursed Mountains and along the Albanian-Macedonian border.' },
    { emoji: '🐎', name: 'Donkey', description: 'Working donkeys still common in rural mountain villages, carrying goods up steep paths where cars cannot go.' },
    { emoji: '🐢', name: 'Mediterranean tortoise', description: 'Sometimes spotted in the dry limestone hills of southern Albania near Saranda and Butrint.' },
    { emoji: '🦊', name: 'Red fox', description: 'Common across Albania, especially in the foothills around villages.' },
    { emoji: '🐻', name: 'Brown bear', description: 'Returning slowly to the Albanian Alps. Population is very small.', olderOnly: true },
    { emoji: '🐺', name: 'Grey wolf', description: 'A small but genuine wolf population in the eastern mountains.', olderOnly: true },
  ],
  montenegro: [
    { emoji: '🐻', name: 'Brown bear', description: 'Lives in the deep forests of Durmitor and Biogradska Gora national parks.' },
    { emoji: '🦌', name: 'Red deer', description: 'In the alpine forests of northern Montenegro, especially Biogradska Gora.' },
    { emoji: '🐺', name: 'Grey wolf', description: 'Wolves have re-established in the Durmitor and Komovi mountain ranges.' },
    { emoji: '🐈', name: 'Kotor cat', description: 'Kotor\'s old town is famously full of cats, lounging on every walls, doorstep and Venetian palace. There is even a cat museum.' },
    { emoji: '🦅', name: 'Golden eagle', description: 'Nests in the high crags of Durmitor National Park. About 50 pairs in the country.' },
    { emoji: '🐍', name: 'Horn-nosed viper', description: 'A venomous viper found in the limestone hills of Montenegro. Shy, gives warning, almost never bites.', olderOnly: true },
    { emoji: '🦦', name: 'Otter', description: 'Returning to the clean waters of the Tara River and Lake Skadar.', olderOnly: true },
  ],
  austria: [
    { emoji: '🐄', name: 'Brown Alpine cow', description: 'Wearing big bells, grazing on summer pastures across the Tyrolean Alps. The bells help farmers find them.' },
    { emoji: '🦌', name: 'Red deer', description: 'In Austrian alpine forests, especially common in the Hohe Tauern National Park.' },
    { emoji: '🐎', name: 'Lipizzaner horse', description: 'The famous white show horses of the Spanish Riding School in Vienna. Bred since 1580.' },
    { emoji: '🦅', name: 'Golden eagle', description: 'Nests in the Austrian Alps, especially in Hohe Tauern. About 350 pairs.' },
    { emoji: '🐻', name: 'Marmot', description: 'Fat, fluffy alpine rodents that whistle loudly when scared. Common in high meadows in summer.' },
    { emoji: '🦌', name: 'Alpine ibex', description: 'A wild mountain goat with huge curved horns, reintroduced to the high Austrian Alps. Around 1,000 in the country.', olderOnly: true },
    { emoji: '🐺', name: 'Grey wolf', description: 'Returning slowly to the Austrian Alps after long absence. A handful of packs documented.', olderOnly: true },
  ],
  ireland: [
    { emoji: '🐑', name: 'Sheep', description: 'Ireland has around 4 million sheep across 130,000 farms. Black-faced mountain sheep, white Suffolks, Connemara breeds.' },
    { emoji: '🐄', name: 'Dairy cow', description: 'Friesian and Holstein dairy cows in every Irish field. Irish dairy (especially butter) is famous worldwide.' },
    { emoji: '🐦', name: 'Atlantic puffin', description: 'Half-pigeon, half-clown. Nests on western islands like Skellig Michael, Saltees, the Cliffs of Moher (May-August).' },
    { emoji: '🦅', name: 'White-tailed eagle', description: 'Reintroduced to Killarney National Park after going extinct in Ireland. Now breeding again, with a 2.5 m wingspan.' },
    { emoji: '🐬', name: 'Common dolphin', description: 'Plays in the bow waves off the west coast of Ireland, especially around the Dingle Peninsula.' },
    { emoji: '🦦', name: 'Otter', description: 'Found in clean Irish rivers and along the west coast in sea estuaries.', olderOnly: true },
    { emoji: '🐎', name: 'Connemara pony', description: 'A small, sturdy native Irish pony breed from the wild west coast. Often grey or dun.', olderOnly: true },
  ],

  // ── NORTH AMERICA ───────────────────────────────────────────────
  canada: [
    { emoji: '🪿', name: 'Canada goose', description: 'Honking V-formations overhead in spring and autumn, lakes in summer.' },
    { emoji: '🐿️', name: 'Eastern chipmunk', description: 'Stripey small ground squirrels in every campground and park.' },
    { emoji: '🦫', name: 'Beaver', description: 'Canada\'s national animal. Dams across streams, especially in Algonquin and the Rockies.' },
    { emoji: '🦌', name: 'White-tailed deer', description: 'At dusk in fields, gardens, even Toronto ravines.' },
    { emoji: '🦅', name: 'Bald eagle', description: 'In British Columbia and the Atlantic provinces, especially around salmon runs.' },
    { emoji: '🐻', name: 'Black bear or grizzly', description: 'In the Rockies, Algonquin, BC coast. Don\'t leave food in your tent!', olderOnly: true },
    { emoji: '🫎', name: 'Moose', description: 'The biggest deer in the world. In Newfoundland, Algonquin, the Rockies, the Yukon.', olderOnly: true },
  ],
  usa: [
    { emoji: '🐿️', name: 'Eastern grey squirrel', description: 'In every park, every backyard, every campus from coast to coast.' },
    { emoji: '🦌', name: 'White-tailed deer', description: 'In suburban gardens, national parks, side of every interstate at dusk.' },
    { emoji: '🦅', name: 'Bald eagle', description: 'America\'s national bird. Best spots: Alaska, the Pacific Northwest, the Mississippi River.' },
    { emoji: '🐻', name: 'Black bear', description: 'In Yellowstone, the Smokies, Yosemite. Don\'t feed them, ever.' },
    { emoji: '🦬', name: 'American bison', description: 'Yellowstone has the only continuously wild herd. Massive, shaggy, can run 50 km/h.' },
    { emoji: '🐊', name: 'American alligator', description: 'In Florida\'s Everglades, on golf courses, anywhere with warm water.', olderOnly: true },
    { emoji: '🐻‍❄️', name: 'Grizzly bear', description: 'In Yellowstone, Glacier National Park, Alaska. Carry bear spray.', olderOnly: true },
  ],
  mexico: [
    { emoji: '🦎', name: 'Iguana', description: 'Big green or grey lizards basking on warm walls and rocks in Yucatán ruins.' },
    { emoji: '🐈', name: 'Mercado cat', description: 'Sleek market cats around every Mexican mercado, fed by stallholders.' },
    { emoji: '🐢', name: 'Sea turtle', description: 'Olive ridley, green and hawksbill turtles nest on Pacific and Caribbean beaches.' },
    { emoji: '🦅', name: 'Crested caracara', description: 'A striking black-and-white raptor with a crest, common in rural Mexico.' },
    { emoji: '🦋', name: 'Monarch butterfly', description: 'In November–March, millions migrate to fir forests in Michoacán. UNESCO listed.', olderOnly: true },
    { emoji: '🐋', name: 'Grey whale', description: 'Birthing calves in Baja California lagoons every winter. Boats can come close.', olderOnly: true },
  ],
  'costa-rica': [
    { emoji: '🦥', name: 'Two-toed or three-toed sloth', description: 'In trees in Manuel Antonio, Tortuguero, anywhere with rainforest. Move very slowly.' },
    { emoji: '🐒', name: 'White-faced capuchin monkey', description: 'Cheeky, intelligent, will absolutely steal your lunch. Common in coastal forests.' },
    { emoji: '🦜', name: 'Scarlet macaw', description: 'Bright red-blue-yellow parrots flying in pairs above the Pacific coast (especially Carara).' },
    { emoji: '🦎', name: 'Iguana', description: 'Green or black, sunning themselves on rocks and tree branches everywhere.' },
    { emoji: '🐸', name: 'Red-eyed tree frog', description: 'Bright green with red eyes and orange feet. Iconic Costa Rican rainforest emblem.', olderOnly: true },
    { emoji: '🦋', name: 'Blue morpho butterfly', description: 'Huge iridescent blue butterfly flashing through the rainforest.', olderOnly: true },
  ],
  jamaica: [
    { emoji: '🐐', name: 'Free-range goat', description: 'Everywhere — eating roadside grass, blocking traffic, lounging in shade.' },
    { emoji: '🐔', name: 'Wandering chicken', description: 'Crossing every village street and clucking at every guesthouse.' },
    { emoji: '🐈', name: 'Yard cat', description: 'Skinny independent cats around every Jamaican kitchen and beach bar.' },
    { emoji: '🦎', name: 'Anole lizard', description: 'Bright green lizards doing push-ups on tropical garden walls.' },
    { emoji: '🦜', name: 'Doctor bird (streamertail hummingbird)', description: 'Jamaica\'s national bird — black-and-green with long tail feathers, only found here.', olderOnly: true },
    { emoji: '🦀', name: 'Land crab', description: 'On road crossings near the coast, especially after rain.', olderOnly: true },
  ],

  // ── SOUTH AMERICA ───────────────────────────────────────────────
  brazil: [
    { emoji: '🐒', name: 'Capuchin monkey', description: 'In Tijuca Forest right above Rio, in any rainforest reserve, sometimes on city walls.' },
    { emoji: '🦜', name: 'Scarlet or blue-and-yellow macaw', description: 'Loud, brilliantly-coloured parrots flying in pairs above the Amazon and Pantanal.' },
    { emoji: '🐊', name: 'Yacare caiman', description: 'In Pantanal rivers and lakes — usually placid, often dozens in one stretch of bank.' },
    { emoji: '🦒', name: 'Capybara', description: 'The world\'s biggest rodent — looks like a chilled-out giant guinea pig. Common in the Pantanal.' },
    { emoji: '🐬', name: 'Pink river dolphin', description: 'In the Amazon. Yes, actually pink. Yes, real.', olderOnly: true },
    { emoji: '🐆', name: 'Jaguar', description: 'The Pantanal is the best place on Earth to spot a wild jaguar, lounging by the riverbank.', olderOnly: true },
  ],
  argentina: [
    { emoji: '🐎', name: 'Gaucho horse', description: 'On every estancia (cattle ranch) across the pampas. Often ridden by gauchos in flat hats.' },
    { emoji: '🐄', name: 'Aberdeen Angus cattle', description: 'Black cows in vast herds — these become the famous Argentine asado beef.' },
    { emoji: '🐧', name: 'Magellanic penguin', description: 'In Punta Tombo and Peninsula Valdés on the Patagonian Atlantic coast.' },
    { emoji: '🦙', name: 'Guanaco', description: 'Wild relative of the llama. Patagonia, Tierra del Fuego, parts of the Andes.' },
    { emoji: '🦅', name: 'Andean condor', description: 'One of the largest flying birds — 3m wingspan, soaring above the Andes.', olderOnly: true },
    { emoji: '🐋', name: 'Southern right whale', description: 'Peninsula Valdés in June–December. Mothers and calves come close to shore.', olderOnly: true },
  ],
  chile: [
    { emoji: '🐕', name: 'Quiltro (Chilean street dog)', description: 'Friendly, mostly cared for by neighbourhoods, often follow you for blocks.' },
    { emoji: '🦙', name: 'Guanaco', description: 'Wild llama-relative, in Patagonia (Torres del Paine) and the Atacama altiplano.' },
    { emoji: '🦅', name: 'Andean condor', description: '3-metre wingspan, soaring above the Andean ridges. National bird.' },
    { emoji: '🦩', name: 'James\'s flamingo', description: 'On high-altitude salt lakes in the Atacama. Pink against turquoise water.' },
    { emoji: '🐧', name: 'Magellanic penguin', description: 'Off the Patagonian coasts and on Isla Magdalena.', olderOnly: true },
    { emoji: '🐆', name: 'Puma', description: 'Torres del Paine has the best wild puma sightings in the world.', olderOnly: true },
  ],
  peru: [
    { emoji: '🦙', name: 'Llama', description: 'Tall, woolly, found everywhere in the highlands. Used for carrying loads up Andean trails for thousands of years.' },
    { emoji: '🦙', name: 'Alpaca', description: 'Smaller and fluffier than a llama, with a much softer fleece. The high-altitude grasslands of Puno and Cusco are full of them.' },
    { emoji: '🐦', name: 'Inca tern', description: 'Striking grey seabird with a curling white moustache, on the Pacific cliffs of the Paracas peninsula.' },
    { emoji: '🦅', name: 'Andean condor', description: 'One of the biggest flying birds on Earth (3 m wingspan). Best seen at Colca Canyon at sunrise.', olderOnly: true },
    { emoji: '🐬', name: 'Pink river dolphin', description: 'In the Peruvian Amazon, around Iquitos. Yes, actually pink.', olderOnly: true },
    { emoji: '🦙', name: 'Vicuña', description: 'The wild ancestor of the alpaca, with the finest wool in the world. Protected, in the high Andean plains.', olderOnly: true },
  ],
  colombia: [
    { emoji: '🦜', name: 'Toucan', description: 'Large beaks, colourful feathers, common in the lowland forests of the Amazon and Pacific.' },
    { emoji: '🐦', name: 'Hummingbird', description: 'Colombia has more bird species than any country, including 165+ kinds of hummingbird. They are everywhere with flowers.' },
    { emoji: '🦋', name: 'Blue morpho butterfly', description: 'Bright electric-blue wings as big as your hand, flashing through the rainforest.' },
    { emoji: '🐒', name: 'Cotton-top tamarin', description: 'Tiny monkeys with a wild white head-tuft, only found in north-west Colombia. Critically endangered.' },
    { emoji: '🐬', name: 'Pink river dolphin', description: 'In the Colombian Amazon around Leticia.', olderOnly: true },
    { emoji: '🦅', name: 'Andean condor', description: 'National bird, found high in the Andes near the snow line.', olderOnly: true },
  ],
  ecuador: [
    { emoji: '🐢', name: 'Giant Galápagos tortoise', description: 'Can live 150+ years and weigh 250 kg. Wandering free on Santa Cruz and Isabela islands.' },
    { emoji: '🦎', name: 'Marine iguana', description: 'The only sea-going lizard in the world, only found in the Galápagos. They sneeze salt out of their nostrils.' },
    { emoji: '🦭', name: 'Galápagos sea lion', description: 'Lying on park benches, beach steps, and harbour walls. Completely unbothered by humans.' },
    { emoji: '🐦', name: 'Blue-footed booby', description: 'Seabird with extraordinary bright blue feet. Does a high-stepping dance to attract a mate.' },
    { emoji: '🐧', name: 'Galápagos penguin', description: 'The only penguin found north of the equator. Tiny, fast, and rare.', olderOnly: true },
    { emoji: '🐦', name: 'Andean cock-of-the-rock', description: 'A bright orange Ecuadorian cloud-forest bird, the national bird of Peru too. Loud, weird, hard to forget.', olderOnly: true },
  ],
  uruguay: [
    { emoji: '🐄', name: 'Hereford / Aberdeen Angus cattle', description: 'Endless herds across the pampas. Uruguay has nearly four cows per person.' },
    { emoji: '🐎', name: 'Gaucho horse', description: 'On every working estancia, ridden by gauchos in flat hats and bombachas (loose riding trousers).' },
    { emoji: '🦭', name: 'South American sea lion', description: 'Huge colony at Cabo Polonio and the Isla de Lobos off Punta del Este, audible from kilometres away.' },
    { emoji: '🦏', name: 'Capybara', description: 'World\'s biggest rodent. Calm, sociable, often napping by rivers and wetlands.' },
    { emoji: '🐦', name: 'Rhea (ñandú)', description: 'A large flightless bird like a small ostrich, running across the pampas.', olderOnly: true },
    { emoji: '🐋', name: 'Southern right whale', description: 'Off the Atlantic coast at La Paloma and Cabo Polonio between July and November.', olderOnly: true },
  ],

  // ── OCEANIA ─────────────────────────────────────────────────────
  australia: [
    { emoji: '🦘', name: 'Eastern grey kangaroo', description: 'Hopping across pastures and along golf courses at dawn and dusk. Everywhere outside the cities.' },
    { emoji: '🐨', name: 'Koala', description: 'Asleep in a eucalyptus tree, usually. Try the Otways, Magnetic Island, Kangaroo Island.' },
    { emoji: '🦜', name: 'Rainbow lorikeet', description: 'Loud, brightly-coloured parrots in every Aussie backyard and tree.' },
    { emoji: '🪿', name: 'Magpie or kookaburra', description: 'Magpies for the songs (and swooping), kookaburras for the laughing call.' },
    { emoji: '🐊', name: 'Saltwater crocodile', description: 'Northern Territory and far North Queensland. NEVER swim where you see "croc" warning signs.', olderOnly: true },
    { emoji: '🦆', name: 'Platypus', description: 'The egg-laying mammal. Best in Tasmanian streams or Eungella National Park in Queensland.', olderOnly: true },
  ],
  'new-zealand': [
    { emoji: '🐑', name: 'Merino or Romney sheep', description: 'New Zealand has 5 sheep for every person. They\'re everywhere.' },
    { emoji: '🦆', name: 'Pukeko', description: 'Bright blue swamp-hen with red beak and big feet, in every wetland and roadside ditch.' },
    { emoji: '🐦', name: 'Tūī', description: 'Black bird with a white throat-tuft and a wild song of clicks, bells and whistles.' },
    { emoji: '🦭', name: 'New Zealand fur seal', description: 'On rocky coasts especially Kaikōura and Cape Palliser. Don\'t get between them and the sea.' },
    { emoji: '🦜', name: 'Kea', description: 'Mountain parrot in the South Island Alps — clever enough to dismantle a car windscreen wiper for fun.', olderOnly: true },
    { emoji: '🥝', name: 'Kiwi bird', description: 'Nocturnal flightless bird, usually only seen in sanctuaries. National icon.', olderOnly: true },
  ],
  italy: [
    { emoji: '🐈', name: 'Street cat', description: 'Italy has millions of street cats — protected by law. Look in Rome\'s ruins (especially Largo di Torre Argentina, the official cat sanctuary).' },
    { emoji: '🐦', name: 'Swallows over piazzas', description: 'In summer they dart and shriek over open squares at dusk, catching insects.' },
    { emoji: '🦆', name: 'Mallard duck', description: 'On every fountain, canal, and park pond — Venice canals are full of them.' },
    { emoji: '🐗', name: 'Wild boar (cinghiale)', description: 'In Tuscan forests, Roman parks, and increasingly on city outskirts. Don\'t approach.' },
    { emoji: '🐎', name: 'Carriage horse', description: 'Pulling tourists around Rome and Florence — declining as cities pass animal welfare rules.' },
    { emoji: '🐻', name: 'Marsican brown bear', description: 'About 50 left in Abruzzo National Park. Critically endangered.', olderOnly: true },
    { emoji: '🐺', name: 'Italian wolf', description: 'Returning to the Apennines after centuries of persecution. Heard more than seen.', olderOnly: true },
  ],
  hungary: [
    { emoji: '🪿', name: 'White stork', description: 'Nesting on chimneys, electricity poles, and church towers across the countryside.' },
    { emoji: '🐂', name: 'Hungarian grey cattle', description: 'Iconic long-horned cattle on the Puszta plains. Hungary\'s national breed.' },
    { emoji: '🐑', name: 'Racka sheep', description: 'Twisted, spiral-shaped horns up to a metre long. Found mainly on the Hortobágy plains.' },
    { emoji: '🐶', name: 'Vizsla', description: 'Russet-coloured Hungarian hunting dog — one of the country\'s most loved breeds.' },
    { emoji: '🦆', name: 'Wild ducks on the Danube', description: 'Mallards, pochards, and tufted ducks along the river right through Budapest.' },
    { emoji: '🦅', name: 'Saker falcon', description: 'Hungary\'s national bird, nesting on castle ruins and farm buildings.', olderOnly: true },
    { emoji: '🦫', name: 'Eurasian beaver', description: 'Returned to Hungarian rivers in the 1990s after centuries of absence.', olderOnly: true },
  ],
  switzerland: [
    { emoji: '🐄', name: 'Alpine cow with bell', description: 'Brown Swiss cows wearing giant bells, herded up to high pastures every summer.' },
    { emoji: '🦅', name: 'Golden eagle', description: 'Above the high peaks — about 350 breeding pairs in the Swiss Alps.' },
    { emoji: '🐐', name: 'Alpine ibex', description: 'Sure-footed wild goats with curved horns, on the steepest cliff faces.' },
    { emoji: '🐿️', name: 'Alpine marmot', description: 'Burrowing rodents — listen for their sharp warning whistle on alpine trails.' },
    { emoji: '🦊', name: 'Red fox', description: 'Common in cities AND mountains. Often spotted at dusk in Zurich and Bern parks.' },
    { emoji: '🐻', name: 'Brown bear', description: 'Returning to eastern Switzerland from Italy after 100+ years gone. Very rare sighting.', olderOnly: true },
    { emoji: '🐺', name: 'Wolf pack', description: 'About 30 wild wolf packs in Switzerland — controversial as they prey on sheep.', olderOnly: true },
  ],
  greece: [
    { emoji: '🐈', name: 'Greek street cat', description: 'On every island, every taverna terrace, every harbour wall. Locals feed them.' },
    { emoji: '🐐', name: 'Mountain goat', description: 'Free-roaming on the islands and mainland hills — sometimes on rooftops.' },
    { emoji: '🫏', name: 'Donkey', description: 'Still used on Santorini and Hydra to carry goods up steep staircases. Animal welfare worth checking before riding.' },
    { emoji: '🐙', name: 'Octopus', description: 'Hanging up to dry outside seaside tavernas — also alive in rock pools if you snorkel.' },
    { emoji: '🐦', name: 'Pelican (Petros family)', description: 'Wild pelicans famous in Mykonos town — adopted by locals since the 1950s.' },
    { emoji: '🐢', name: 'Loggerhead turtle', description: 'Nesting on Zakynthos beaches between June and October. Strict protections in place.', olderOnly: true },
    { emoji: '🦭', name: 'Mediterranean monk seal', description: 'One of the world\'s rarest seals — about 700 left, mostly in the Greek Aegean.', olderOnly: true },
  ],
  sweden: [
    { emoji: '🫎', name: 'Moose (älg)', description: 'Sweden\'s "king of the forest". Around 350,000 live in the woods. Best spotted at dusk.' },
    { emoji: '🐿️', name: 'Red squirrel', description: 'Russet with tufted ears, in any forest or city park.' },
    { emoji: '🦌', name: 'Reindeer', description: 'Herded by the Sámi in the north. Can wander onto roads, especially around Kiruna.' },
    { emoji: '🦫', name: 'European beaver', description: 'Common in Swedish rivers and lakes. Look for gnawed tree stumps.' },
    { emoji: '🪿', name: 'Common crane', description: 'Spring and autumn — thousands migrate through Lake Hornborga in a famous "crane dance" gathering.' },
    { emoji: '🐻', name: 'Brown bear', description: 'About 3,000 in Sweden\'s north and central forests. Shy — they almost always hear you first.', olderOnly: true },
    { emoji: '🐺', name: 'Wolf', description: 'Around 400 wolves in Sweden, mostly in the south-central forests. Strictly protected.', olderOnly: true },
  ],
  norway: [
    { emoji: '🦌', name: 'Reindeer', description: 'Both wild and herded by the Sámi. Often cross the road in the north.' },
    { emoji: '🫎', name: 'Moose', description: 'The largest land animal in Norway — found in forests throughout the country.' },
    { emoji: '🦅', name: 'White-tailed sea eagle', description: 'Huge wingspan — common along the coast, especially in Lofoten.' },
    { emoji: '🐟', name: 'Atlantic salmon', description: 'Wild salmon leap up Norwegian rivers in summer to spawn. World-famous fishing.' },
    { emoji: '🦭', name: 'Harbour seal', description: 'Hauling out on rocks along the fjords — sometimes pop their heads up next to boats.' },
    { emoji: '🐻‍❄️', name: 'Polar bear', description: 'Only on Svalbard archipelago in the Arctic. About 3,000 there — outnumber humans on those islands.', olderOnly: true },
    { emoji: '🦊', name: 'Arctic fox', description: 'Tiny white fox in the mountains and the far north. About 300 left in Norway.', olderOnly: true },
  ],
  denmark: [
    { emoji: '🪿', name: 'White stork', description: 'Returning to Denmark after near-extinction in the 1990s — now around 6 nesting pairs, watched carefully.' },
    { emoji: '🦢', name: 'Mute swan', description: 'Denmark\'s national bird (Hans Christian Andersen\'s "Ugly Duckling" was a young swan). On every lake and harbour.' },
    { emoji: '🦌', name: 'Red deer', description: 'In Jutland forests and Danish national parks. Largest land mammal in the country.' },
    { emoji: '🦭', name: 'Harbour seal', description: 'Along the North Sea and Wadden Sea coasts — colonies you can visit on boat tours.' },
    { emoji: '🦔', name: 'European hedgehog', description: 'In gardens and parks, often crossing pavements at dusk. Beloved in Denmark.' },
    { emoji: '🐬', name: 'Harbour porpoise', description: 'Small dolphin species in the Belt Sea — sometimes glimpsed from ferries.', olderOnly: true },
    { emoji: '🦅', name: 'White-tailed eagle', description: 'Recovered from near-extinction — about 200 pairs now nest in Denmark.', olderOnly: true },
  ],
  poland: [
    { emoji: '🪿', name: 'White stork', description: 'Poland has more storks than any other country — about 50,000 nesting pairs. They\'re seen as good luck.' },
    { emoji: '🦬', name: 'European bison (żubr)', description: 'Europe\'s largest land mammal — about 800 live wild in Białowieża Forest. The species was saved from extinction here.' },
    { emoji: '🐗', name: 'Wild boar', description: 'Increasingly common — even in Polish city parks at night.' },
    { emoji: '🦌', name: 'Red deer', description: 'In forests across the country. You can hear males roaring in autumn.' },
    { emoji: '🐝', name: 'Honey bee', description: 'Polish beekeepers produce 25,000 tonnes of honey a year. Wooden bee hives in countryside.' },
    { emoji: '🐻', name: 'Brown bear', description: 'About 100 in the Tatra and Bieszczady mountains. Strictly protected.', olderOnly: true },
    { emoji: '🐺', name: 'Grey wolf', description: 'Around 3,000 in Poland — biggest population in central Europe. Hunting them is illegal.', olderOnly: true },
  ],
  latvia: [
    { emoji: '🪿', name: 'White stork', description: 'Latvia has one of the highest stork densities in Europe — nests on chimneys, poles, even traffic lights.' },
    { emoji: '🦫', name: 'Eurasian beaver', description: 'Very common in Latvian rivers — look for dams and gnawed trees.' },
    { emoji: '🐗', name: 'Wild boar', description: 'In forests and increasingly close to farms. Often seen at dawn.' },
    { emoji: '🦌', name: 'Red deer', description: 'In Gauja National Park and the eastern forests.' },
    { emoji: '🫎', name: 'Eurasian elk (moose)', description: 'Common in Latvian forests — about 25,000 in the country.' },
    { emoji: '🐻', name: 'Brown bear', description: 'Slowly returning from Russia. Maybe 10–15 wandering bears, mostly in the east.', olderOnly: true },
    { emoji: '🐺', name: 'Grey wolf', description: 'Around 500 wolves in Latvia\'s deep forests. Hunted in winter under strict quotas.', olderOnly: true },
  ],
  lithuania: [
    { emoji: '🪿', name: 'White stork', description: 'Lithuania\'s national bird — there\'s a stork in almost every village in summer.' },
    { emoji: '🦫', name: 'European beaver', description: 'Common in Lithuanian rivers and wetlands.' },
    { emoji: '🫎', name: 'Eurasian elk (moose)', description: 'In Lithuanian forests, especially in the Dzūkija and Aukštaitija national parks.' },
    { emoji: '🐗', name: 'Wild boar', description: 'Common in farmland and forest edges. Numbers controlled by hunting.' },
    { emoji: '🦌', name: 'Red deer', description: 'In forests, especially the south. Watch at dawn near forest edges.' },
    { emoji: '🐺', name: 'Grey wolf', description: 'About 400 wolves in Lithuanian forests. Numbers stable.', olderOnly: true },
    { emoji: '🐱', name: 'Eurasian lynx', description: 'Lithuania has Europe\'s healthiest lynx population — about 200, in deep forests.', olderOnly: true },
  ],
  romania: [
    { emoji: '🐻', name: 'Brown bear', description: 'Romania has Europe\'s biggest brown bear population — around 8,000 in the Carpathian mountains.' },
    { emoji: '🐗', name: 'Wild boar', description: 'Everywhere — Carpathian forests, lowland farmland, even occasionally on Bucharest outskirts.' },
    { emoji: '🦌', name: 'Red deer', description: 'Carpathian forests — listen for the roaring males in autumn.' },
    { emoji: '🐎', name: 'Horse-drawn cart pony', description: 'Working horses still pull carts in rural Maramureș and Transylvanian villages.' },
    { emoji: '🦢', name: 'Pelican', description: 'White pelicans and Dalmatian pelicans in the Danube Delta — Europe\'s biggest pelican colony.' },
    { emoji: '🐺', name: 'Grey wolf', description: 'About 2,500 wolves in the Carpathians — biggest wolf population in Europe outside Russia.', olderOnly: true },
    { emoji: '🐱', name: 'Eurasian lynx', description: 'Around 1,500 lynx in the Carpathians, the largest population in central/eastern Europe.', olderOnly: true },
  ],
  iceland: [
    { emoji: '🐑', name: 'Icelandic sheep', description: 'Stocky, double-coated, often horned. Roam freely on hillsides all summer. There are more sheep than people in Iceland.' },
    { emoji: '🐴', name: 'Icelandic horse', description: 'Short, shaggy, brought by the Vikings 1,000+ years ago, and never crossbred since. Has FIVE gaits instead of four.' },
    { emoji: '🐦', name: 'Atlantic puffin', description: 'Half of the world\'s Atlantic puffins nest in Iceland. Best places: the Westman Islands and Látrabjarg cliffs, May to August.' },
    { emoji: '🦅', name: 'White-tailed eagle', description: 'Iceland\'s biggest bird of prey, with a 2.5 m wingspan. About 80 breeding pairs left, mostly in the Westfjords.' },
    { emoji: '🐋', name: 'Humpback whale', description: 'Húsavík in the north is the whale-watching capital of Europe. Humpbacks breach right next to the boats.', olderOnly: true },
    { emoji: '🦊', name: 'Arctic fox', description: 'Iceland\'s only native land mammal, here since the Ice Age. Pure white in winter, brown in summer.', olderOnly: true },
  ],
}
