// Pack content loader.
//
// Previously this file held every pack's full content inline (1.13 MB
// across 93 packs), and it was bundled into the Cloudflare Worker on
// every deploy. As the catalogue grew it was pushing the worker close
// to its size limit and slowing every cold start.
//
// Now each pack lives as its own JSON file under public/data/packs/
// (generated by scripts/extract-pack-json.ts at content-edit time), and
// this loader fetches them on demand. Cloudflare serves the JSON files
// straight from edge cache so the round trip is fast.

import type { AdventurePackData } from './adventurePackTypes'

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3000'

export async function getPackData(slug: string): Promise<AdventurePackData | null> {
  try {
    const res = await fetch(`${SITE_URL}/data/packs/${encodeURIComponent(slug)}.json`)
    if (!res.ok) return null
    return (await res.json()) as AdventurePackData
  } catch {
    return null
  }
}

// Re-export so existing `import { getPackMeta } from '@/lib/adventurePackData'`
// callers don't need to change their imports.
export { getPackMeta } from './adventurePackMeta'
