// Adventure Pack content registry.
//
// FRANCE_DATA is fully populated. This is the free pack and acts as
// the quality reference for every other country pack. Other countries
// have meta entries only (so they show on the listing as "Coming soon")
// until we write their content.

import type {
  AdventurePackData, AdventurePackMeta,
} from './adventurePackTypes'

// ── FRANCE (live + free) ─────────────────────────────────────────
export const FRANCE_DATA: AdventurePackData = {
  slug: 'france',
  country: 'France',
  flag: '🇫🇷',
  iso2: 'fr',
  isFree: true,
  heroColour: 'bg-brand-900',
  currency: {
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    recommendedBudget: 20,
    budgetNote: 'Recommended: 20 €',
  },
  mapQuestions: [
    { question: 'Which continent is France on?', answer: 'Europe 🌍' },
    { question: 'What sea and ocean touch France?', answer: 'The Mediterranean Sea and the Atlantic Ocean 🌊' },
    { question: 'What is the capital of France?', answer: 'Paris. About 12 million people live in the wider Paris area.' },
    { question: 'Name 3 countries that border France', answer: 'Spain, Italy, Belgium, Germany, Switzerland and Luxembourg. Pick any 3.', olderOnly: true },
    { question: 'What is the highest mountain in France (and Western Europe)?', answer: 'Mont Blanc, 4,808 metres, in the French Alps near Italy.', olderOnly: true },
  ],
  phrases: [
    { english: 'Hello', nativeScript: 'Bonjour', nativeLatin: 'Bonjour', phonetic: 'bon-zhoor', lang: 'fr' },
    { english: 'Thank you', nativeScript: 'Merci', nativeLatin: 'Merci', phonetic: 'mair-see', lang: 'fr' },
    { english: 'Please', nativeScript: "S'il vous plaît", nativeLatin: "S'il vous plaît", phonetic: 'see voo play', lang: 'fr' },
    { english: 'How much?', nativeScript: "C'est combien ?", nativeLatin: "C'est combien ?", phonetic: 'say com-bee-an', lang: 'fr' },
    { english: 'Delicious!', nativeScript: "C'est délicieux !", nativeLatin: "C'est délicieux !", phonetic: 'say day-lee-syuh', lang: 'fr' },
    { english: 'Goodbye', nativeScript: 'Au revoir', nativeLatin: 'Au revoir', phonetic: 'oh ruh-vwar', lang: 'fr' },
    { english: 'Excuse me', nativeScript: 'Excusez-moi', nativeLatin: 'Excusez-moi', phonetic: 'ex-koo-zay mwah', lang: 'fr', olderOnly: true },
    { english: 'I would like…', nativeScript: 'Je voudrais…', nativeLatin: 'Je voudrais…', phonetic: 'zhuh voo-dray', lang: 'fr', olderOnly: true },
  ],
  foods: [
    { emoji: '🥐', name: 'Croissant', description: 'Flaky, buttery breakfast pastry, best fresh from a boulangerie before 10am.' },
    { emoji: '🥖', name: 'Baguette', description: 'Long crusty bread loaf. Carry it home under your arm like a local.' },
    { emoji: '🧀', name: 'Cheese plate', description: 'France makes over 400 cheeses. Try Brie, Comté, Roquefort, and one stinky one.' },
    { emoji: '🥞', name: 'Crêpes', description: 'Thin pancakes, sweet with Nutella and banana, or savoury with ham and cheese.' },
    { emoji: '🍫', name: 'Pain au chocolat', description: 'A croissant with two strips of dark chocolate inside. The breakfast of champions.' },
    { emoji: '🍲', name: 'Ratatouille', description: 'A slow-cooked vegetable stew from the south, with courgettes, peppers, aubergine and tomatoes.' },
  ],
  scavengerItems: [
    { emoji: '🚲', label: 'Someone cycling with a baguette in the basket' },
    { emoji: '🥐', label: 'A boulangerie (bakery) sign' },
    { emoji: '🏛️', label: 'A statue of someone famous in a square' },
    { emoji: '🐩', label: 'A small dog being treated like a person' },
    { emoji: '⛲', label: 'A fountain' },
    { emoji: '🪟', label: 'Houses with bright blue shutters' },
    { emoji: '🥖', label: 'A queue outside a bakery' },
    { emoji: '🎨', label: 'A street artist painting or sketching' },
    { emoji: '☕', label: 'A pavement café with people watching the world go by' },
    { emoji: '🏰', label: 'A château (castle) on a hill', olderOnly: true },
    { emoji: '⚜️', label: 'The fleur-de-lis symbol on a building or sign', olderOnly: true },
    { emoji: '📜', label: 'A plaque on a wall in French, read what it says', olderOnly: true },
  ],
  geoMatches: [
    { place: 'Paris',         emoji: '🗼', description: 'The capital. The Eiffel Tower, the Louvre, the Seine, and the best croissants you will ever eat.' },
    { place: 'Provence',      emoji: '💜', description: 'Sunny south, with lavender fields, olive trees, rosé wine, and pretty stone villages.' },
    { place: 'The Alps',      emoji: '🏔️', description: 'Snow-capped mountains in the east. Skiing in winter, hiking and lakes in summer.' },
    { place: 'Brittany',      emoji: '🌊', description: 'Wild Atlantic coast in the west, with crêpes, cider, and dramatic granite cliffs.' },
    { place: 'Loire Valley',  emoji: '🏰', description: 'Hundreds of fairy-tale castles along a river, built by kings hundreds of years ago.' },
  ],
  senses: {
    smell: 'Fresh bread, coffee, cheese, river water at dawn, sometimes Gauloise cigarettes…',
    hear:  'Church bells, café chatter, accordion music, the scrape of chairs on cobbles, "Bonjour !" everywhere…',
    taste: 'Salty butter, melting cheese, the crunch of a fresh croissant, dark chocolate, fizzy water…',
    feel:  'Cool stone in old churches, warm sun in a square, sticky pastry on your fingers, river breeze on a bridge…',
    see:   'What is the most incredible thing right in front of you right now…',
  },
  stories: [
    {
      location: '📍 Paris',
      question: 'Why does the Eiffel Tower exist?',
      body: 'The Eiffel Tower was built for the 1889 World Fair, to celebrate 100 years since the French Revolution. At the time, most Parisians HATED it. Writers signed petitions calling it an ugly iron monster. It was only supposed to stand for 20 years and then be torn down. But it turned out to be useful as a radio antenna, and slowly Parisians stopped complaining. Now around 7 million people climb it every year.',
    },
    {
      location: '📍 Everywhere in France',
      question: 'Why do the French eat so much bread?',
      body: 'Bread has been at the centre of French life for over a thousand years. There used to be a law saying every village must have a bakery within walking distance of every house. The French still eat about half a baguette per person per day. Real French bread has only four ingredients (flour, water, salt, yeast) and it goes stale within a day, which is why people buy it fresh every single morning.',
      thinkingQuestion: 'If every village had to have a bakery, what is one other thing you think every family should be able to walk to from home?',
    },
    {
      location: '📍 Versailles',
      question: 'Why is the Palace of Versailles so over-the-top?',
      body: 'Versailles was built by King Louis XIV (the "Sun King") in the 1600s. He turned a small hunting lodge into the most lavish palace in Europe, with 2,300 rooms, a hall of mirrors, and gardens so big you cannot walk them in a day. The whole point was to show off French power. He even made his nobles live there with him so he could keep an eye on them. The whole project nearly bankrupted France, and around 100 years later, that anger helped trigger the French Revolution.',
    },
    {
      location: '📍 Paris, 1789',
      question: 'What was the French Revolution?',
      body: 'In 1789, ordinary French people had had enough. The kings and nobles lived in palaces while everyone else starved. On 14 July, a Paris crowd stormed the Bastille, a prison that symbolised royal power. The revolution that followed eventually overthrew the monarchy, declared "Liberté, Égalité, Fraternité" (liberty, equality, brotherhood) and changed not just France but the whole world. That date, Bastille Day, is still France\'s biggest national holiday.',
      olderOnly: true,
      thinkingQuestion: 'The revolutionaries believed three things every person deserved: liberty, equality, and brotherhood. Which one do you think is the hardest to actually make happen?',
    },
    {
      location: '📍 Normandy',
      question: 'Why are there beaches in France named after letters and code words?',
      body: 'On 6 June 1944, near the end of World War 2, around 156,000 American, British and Canadian soldiers landed on five beaches along the Normandy coast in northern France. The beaches were given the code names Utah, Omaha, Gold, Juno and Sword. France had been occupied by Nazi Germany for four years, and this was the start of taking it back. It was the largest seaborne invasion in history. Today the beaches are quiet sand and dunes again, but you can still find concrete bunkers, huge war cemeteries and museums all along the coast. Small French towns still hold ceremonies to thank the soldiers every June.',
      olderOnly: true,
      thinkingQuestion: 'Why do you think small French towns still hold ceremonies for soldiers who died over 80 years ago?',
    },
  ],
  convoQuestions: [
    { question: 'What\'s the best thing you\'ve eaten in France so far?' },
    { question: 'What\'s one thing the French do better than back home?' },
    { question: 'What\'s one thing that\'s harder here than at home?' },
    { question: 'If you had to live in one French region forever, which one would it be?' },
    { question: 'What\'s been the biggest surprise since we got here?' },
    { question: 'What\'s one French habit you\'d like to bring home with you?', olderOnly: true },
  ],
}

// ── MOROCCO (premium, live) ──────────────────────────────────────
export const MOROCCO_DATA: AdventurePackData = {
  slug: 'morocco',
  country: 'Morocco',
  flag: '🇲🇦',
  iso2: 'ma',
  isFree: false,
  heroColour: 'bg-amber-900',
  currency: {
    code: 'MAD',
    name: 'Moroccan Dirham',
    symbol: 'DH',
    recommendedBudget: 40,
    budgetNote: 'Recommended: 40 DH',
  },
  mapQuestions: [
    { question: 'Which continent is Morocco on?', answer: 'Africa, in the north-west corner closest to Europe 🌍' },
    { question: 'What sea and ocean touch Morocco?', answer: 'The Atlantic Ocean on the west and the Mediterranean Sea on the north 🌊' },
    { question: 'What is the capital of Morocco?', answer: 'Rabat. Most people guess Marrakech or Casablanca, but the capital is actually Rabat on the Atlantic coast.' },
    { question: 'Which big country borders Morocco to the east?', answer: 'Algeria. The border has been closed since 1994, you cannot cross it.', olderOnly: true },
    { question: 'What is the highest mountain in Morocco?', answer: 'Mount Toubkal, 4,167 metres, in the High Atlas mountains south of Marrakech. People climb it in two days.', olderOnly: true },
    { question: 'What huge desert covers part of Morocco?', answer: 'The Sahara, the largest hot desert in the world. It stretches across ten countries.', olderOnly: true },
  ],
  phrases: [
    { english: 'Hello (peace)', nativeScript: 'السلام عليكم', nativeLatin: 'Salam aleikum', phonetic: 'sa-LAM a-LAY-koom', lang: 'ar' },
    { english: 'Thank you', nativeScript: 'شكرا', nativeLatin: 'Shukran', phonetic: 'SHOOK-ran', lang: 'ar' },
    { english: 'Please', nativeScript: 'عافاك', nativeLatin: 'Afak', phonetic: 'AH-fak', lang: 'ar' },
    { english: 'How much?', nativeScript: 'بشحال؟', nativeLatin: 'Bshhal?', phonetic: 'b-SHAH-al', lang: 'ar' },
    { english: 'Delicious!', nativeScript: 'بنين!', nativeLatin: 'Bnin!', phonetic: 'b-NEEN', lang: 'ar' },
    { english: 'Goodbye', nativeScript: 'بسلامة', nativeLatin: 'Beslama', phonetic: 'bess-LAH-ma', lang: 'ar' },
    { english: 'No thank you', nativeScript: 'لا شكرا', nativeLatin: 'La, shukran', phonetic: 'lah SHOOK-ran', lang: 'ar', olderOnly: true },
    { english: 'I would like…', nativeScript: '…بغيت', nativeLatin: 'Bghit…', phonetic: 'b-GHEET', lang: 'ar', olderOnly: true },
  ],
  foods: [
    { emoji: '🍲', name: 'Tagine', description: 'Slow-cooked stew named after the conical clay pot it cooks in. Chicken with preserved lemon, or lamb with prunes, are classics.' },
    { emoji: '🍵', name: 'Mint tea', description: 'Sweet green tea with fresh mint, poured from high up into small glasses. Refuse a glass at your own peril, it is offered everywhere.' },
    { emoji: '🍛', name: 'Couscous', description: 'Tiny steamed pasta with vegetables, chickpeas, and usually lamb or chicken. Traditionally eaten on Fridays after midday prayer.' },
    { emoji: '🥖', name: 'Khobz', description: 'Round flat bread, baked fresh every morning. Used as a spoon to scoop up tagine. Forks are optional, bread is not.' },
    { emoji: '🥧', name: 'Pastilla', description: 'A sweet-and-savoury pie. Shredded chicken or pigeon inside, dusted with cinnamon and icing sugar on top. Sounds wrong, tastes amazing.' },
    { emoji: '🫒', name: 'Olives & preserved lemons', description: 'Bowls of them on every table. The lemons are salted whole and left for weeks, they taste nothing like a fresh lemon.' },
  ],
  scavengerItems: [
    { emoji: '🫖', label: 'Mint tea being poured from really high up' },
    { emoji: '🐈', label: 'A cat curled up asleep in the medina (there are a LOT of cats)' },
    { emoji: '🚪', label: 'A bright blue painted door' },
    { emoji: '🐴', label: 'A donkey carrying things through narrow alleys' },
    { emoji: '🧵', label: 'A handmade Berber rug or carpet' },
    { emoji: '🟫', label: 'A clay tagine pot stacked outside a shop' },
    { emoji: '⛲', label: 'A fountain covered in colourful geometric tiles (zellige)' },
    { emoji: '🌿', label: 'A pile of fresh mint at a market stall' },
    { emoji: '🕌', label: 'A minaret (tall mosque tower) above the rooftops' },
    { emoji: '🧶', label: 'A craftsperson hammering brass or weaving on a loom', olderOnly: true },
    { emoji: '⭐', label: 'The five-pointed star on the Moroccan flag, on a building or sign', olderOnly: true },
    { emoji: '🧭', label: 'A moment where you are completely lost in the medina (it will happen)', olderOnly: true },
  ],
  geoMatches: [
    { place: 'Marrakech',     emoji: '🌆', description: 'The red city. Famous medina, snake charmers and storytellers in the huge Jemaa el-Fna square, and souks that go on forever.' },
    { place: 'Fez',           emoji: '🏛️', description: 'The oldest medina in the world, a 1,200-year-old maze of 9,000 alleys. Home to the world\'s oldest still-running university.' },
    { place: 'Chefchaouen',   emoji: '🔵', description: 'A small mountain town where almost every wall is painted blue. Nobody fully agrees on why.' },
    { place: 'The Sahara',    emoji: '🐪', description: 'Vast orange sand dunes in the south-east. People ride camels and sleep in Berber tents under the stars.' },
    { place: 'Atlas Mountains', emoji: '🏔️', description: 'Tall snow-capped mountains running across the country. Berber villages cling to the valleys.' },
    { place: 'Essaouira',     emoji: '🌊', description: 'Windswept Atlantic coast town. Blue fishing boats, fresh seafood, and a constant breeze that makes the heat bearable.' },
  ],
  senses: {
    smell: 'Mint, cumin and cinnamon in the souk, leather from the tanneries, sweet pastries, charcoal smoke from grills, sometimes diesel and donkey…',
    hear:  'The call to prayer five times a day, sellers shouting prices, motorbikes weaving through alleys, the slap of bread dough, "Bonjour my friend!" from every shop…',
    taste: 'Very sweet mint tea, salty olives, warm cinnamon on pastilla, the crunch of fresh bread, sticky honey pastries, the deep slow flavour of tagine…',
    feel:  'Cool tile underfoot in a riad, warm desert sand between your toes, the scratch of a wool rug, sticky midday heat in the medina, sudden cold at night in the mountains…',
    see:   'What is the most incredible thing right in front of you right now…',
  },
  stories: [
    {
      location: '📍 Marrakech',
      question: 'Why is Jemaa el-Fna square so wild?',
      body: 'Jemaa el-Fna is the huge square in the middle of Marrakech and it has been a meeting place for nearly a thousand years. During the day it is full of orange-juice carts, snake charmers and henna painters. At sunset the food stalls roll in and the whole square turns into a smoky open-air restaurant with hundreds of tables. UNESCO actually protects the square as "intangible heritage" because of its storytellers, the men in robes who sit in a circle and tell tales from memory, a tradition that goes back centuries.',
    },
    {
      location: '📍 Fez',
      question: 'Why is the medina of Fez so confusing?',
      body: 'The medina of Fez is the oldest still-living medieval city in the world, built more than 1,200 years ago. It has around 9,000 alleys, some so narrow you have to turn sideways. There are no cars inside, the only deliveries are by donkey or handcart. The alleys were deliberately designed to confuse invaders, and they still confuse everyone else. Locals say if you ask a child for directions, give them a coin. If they ask first, give them nothing, they will probably take you in circles.',
    },
    {
      location: '📍 Fez',
      question: 'What is the oldest university in the world?',
      body: 'It is here in Fez. The University of al-Qarawiyyin was founded in the year 859, more than 1,100 years ago, which makes it older than Oxford and Cambridge. The wild bit: it was founded by a woman named Fatima al-Fihri, who used her inheritance to build a school and mosque for her community. It is still operating today as both a mosque and a university, and the building has been continuously running longer than almost anything else on earth.',
      olderOnly: true,
      thinkingQuestion: 'Fatima built a school instead of keeping the money. If someone gave you a huge amount of money but said you had to spend it on something for other people, what would you build?',
    },
    {
      location: '📍 Chefchaouen',
      question: 'Why is the whole town painted blue?',
      body: 'Chefchaouen sits high in the Rif Mountains, and almost every wall, door and step is painted some shade of blue. Nobody fully agrees on why. The most popular story is that Jewish refugees who came here in the 1930s brought a tradition of painting buildings blue to symbolise the sky and heaven. Other people say the blue keeps mosquitoes away, or that it keeps the houses cool in summer. Whatever the real answer, the town now has to repaint itself every few months to keep it looking right.',
      thinkingQuestion: 'If you could paint your whole town one colour, which colour would you choose, and why?',
    },
    {
      location: '📍 The Sahara',
      question: 'Who lives in the desert?',
      body: 'The Berbers, who call themselves Amazigh meaning "free people", have lived in north Africa for thousands of years, long before Arabs arrived. In the Sahara some of them are still nomads, moving with camels and goats between water sources. They navigate by stars, and they have a tea ritual where the first glass is poured bitter, the second sweeter, and the third sweetest of all. The saying goes: "the first is bitter like life, the second is sweet like love, the third is gentle like death." They serve all three to any visitor, and you are meant to drink all three.',
      olderOnly: true,
    },
  ],
  convoQuestions: [
    { question: 'What\'s the best thing you\'ve eaten in Morocco so far?' },
    { question: 'What\'s harder here than at home?' },
    { question: 'If we got separated in the medina, what would you do?' },
    { question: 'How did haggling for something go? Did you get a fair price?' },
    { question: 'Which place has felt the most different from home?' },
    { question: 'Would you rather live in a busy city like Marrakech, or a quiet mountain village in the Atlas?', olderOnly: true },
  ],
}

// ── INDONESIA (premium, live) ────────────────────────────────────
export const INDONESIA_DATA: AdventurePackData = {
  slug: 'indonesia',
  country: 'Indonesia',
  flag: '🇮🇩',
  iso2: 'id',
  isFree: false,
  heroColour: 'bg-rose-700',
  currency: {
    code: 'IDR',
    name: 'Indonesian Rupiah',
    symbol: 'Rp',
    recommendedBudget: 200000,
    budgetNote: 'Recommended: Rp200,000 (about £10)',
  },
  mapQuestions: [
    { question: 'Which continent is Indonesia on?', answer: 'Asia, in the south-east. It sits on the equator between mainland Asia and Australia 🌏' },
    { question: 'How many islands does Indonesia have?', answer: 'Over 17,000 islands. Only about 6,000 of them are inhabited, the rest are empty.' },
    { question: 'What is the capital of Indonesia?', answer: 'Jakarta, on the island of Java. It is one of the biggest cities in the world, with over 30 million people in the wider area. (They are building a brand new capital city called Nusantara on Borneo.)' },
    { question: 'Which big country is just south of Indonesia?', answer: 'Australia. From northern Australia you can almost see Indonesia across the Timor Sea.', olderOnly: true },
    { question: 'What is the most active volcano in Indonesia?', answer: 'Mount Merapi on Java, which erupts every few years. Indonesia sits on the Pacific Ring of Fire, so it has around 130 active volcanoes, more than any other country.', olderOnly: true },
  ],
  phrases: [
    { english: 'Hello', nativeScript: 'Halo', nativeLatin: 'Halo', phonetic: 'HA-loh', lang: 'id' },
    { english: 'Thank you', nativeScript: 'Terima kasih', nativeLatin: 'Terima kasih', phonetic: 'tuh-REE-ma KAH-see', lang: 'id' },
    { english: 'Please', nativeScript: 'Tolong', nativeLatin: 'Tolong', phonetic: 'TOH-long', lang: 'id' },
    { english: 'How much?', nativeScript: 'Berapa harganya?', nativeLatin: 'Berapa harganya?', phonetic: 'buh-RAH-pa har-GA-nya', lang: 'id' },
    { english: 'Delicious!', nativeScript: 'Enak!', nativeLatin: 'Enak!', phonetic: 'eh-NAK', lang: 'id' },
    { english: 'Goodbye', nativeScript: 'Selamat tinggal', nativeLatin: 'Selamat tinggal', phonetic: 'suh-LA-mat TING-gal', lang: 'id' },
    { english: 'Excuse me / sorry', nativeScript: 'Permisi / maaf', nativeLatin: 'Permisi / maaf', phonetic: 'pair-MEE-see / MA-af', lang: 'id', olderOnly: true },
    { english: 'I would like…', nativeScript: 'Saya mau…', nativeLatin: 'Saya mau…', phonetic: 'SA-ya MOW', lang: 'id', olderOnly: true },
  ],
  foods: [
    { emoji: '🍚', name: 'Nasi goreng', description: 'Fried rice with sweet soy sauce (kecap manis), egg on top, crispy shallots, and usually chicken or prawns. The unofficial national dish.' },
    { emoji: '🍢', name: 'Sate', description: 'Small skewers of chicken, beef or goat grilled over charcoal, served with thick peanut sauce. The smell from a sate cart at dusk is unforgettable.' },
    { emoji: '🥗', name: 'Gado-gado', description: 'A mix of steamed vegetables, boiled egg, tofu and tempeh, drenched in peanut sauce. "Gado-gado" literally means "mix-mix".' },
    { emoji: '🍛', name: 'Rendang', description: 'Beef slow-cooked for hours in coconut milk and spices until it is dark, dry and unbelievably rich. Once voted the most delicious dish in the world.' },
    { emoji: '🍜', name: 'Mie goreng', description: 'Fried noodles with sweet soy, chilli, vegetables, and usually a fried egg on top. Same family as nasi goreng but with noodles.' },
    { emoji: '🥞', name: 'Martabak manis', description: 'A thick sweet pancake folded over chocolate, condensed milk, peanuts and grated cheese. Sounds chaotic, tastes incredible.' },
  ],
  scavengerItems: [
    { emoji: '🛵', label: 'A whole family riding on one scooter (it really happens)' },
    { emoji: '🪷', label: 'A small basket of flower offerings on a doorstep or pavement (canang sari)' },
    { emoji: '🌾', label: 'A bright green rice terrace' },
    { emoji: '🥥', label: 'Someone selling fresh coconuts with a straw' },
    { emoji: '🛺', label: 'A becak (a bicycle with a passenger seat in front)' },
    { emoji: '🦎', label: 'A small gecko on a wall (and listen for its loud chirp at night)' },
    { emoji: '🌶️', label: 'A bowl of sambal chilli sauce on a table' },
    { emoji: '🐒', label: 'A long-tailed macaque trying to steal something' },
    { emoji: '🪁', label: 'A huge kite flying high in the sky (Indonesia loves kites)' },
    { emoji: '🛕', label: 'A stone temple gate (a "candi bentar" split gate) in Bali', olderOnly: true },
    { emoji: '🎭', label: 'A wayang (shadow puppet) or a traditional mask in a shop', olderOnly: true },
    { emoji: '🌋', label: 'A volcano in the distance (Indonesia has 130 active ones)', olderOnly: true },
  ],
  geoMatches: [
    { place: 'Bali',         emoji: '🌺', description: 'Small island, huge personality. Surf beaches in the south, volcanoes and rice terraces in the centre, temples on every corner.' },
    { place: 'Jakarta',      emoji: '🏙️', description: 'The mega-capital on Java. Skyscrapers, traffic jams that can last hours, and some of the best street food in the country.' },
    { place: 'Yogyakarta',   emoji: '🏛️', description: 'The cultural heart of Java. Home to a sultan, batik workshops, and the gigantic 1,200-year-old Buddhist temple of Borobudur.' },
    { place: 'Komodo Islands', emoji: '🦎', description: 'Dry, golden islands where Komodo dragons (the biggest lizards on earth) roam. You can only visit with a ranger holding a forked stick.' },
    { place: 'Sumatra',      emoji: '🐅', description: 'A huge wild island in the west. Jungles with orangutans and tigers, lakes inside ancient volcanoes, and the spiciest food in Indonesia.' },
    { place: 'Raja Ampat',   emoji: '🐠', description: 'Hundreds of jungle-covered islands in the far east. The most biodiverse coral reefs anywhere on the planet, full of reef sharks and turtles.' },
  ],
  senses: {
    smell: 'Frangipani flowers, clove cigarettes (kretek), sate smoke, durian fruit, jasmine incense from temple offerings, rain on hot tarmac…',
    hear:  'Gamelan music drifting from a courtyard, scooter horns, the call to prayer, geckos chirping at night, roosters at 4am whether you like it or not…',
    taste: 'Spicy sambal, sweet kecap manis, salty crispy shallots, cooling coconut water, sticky palm sugar, the punch of a fresh chilli…',
    feel:  'Sticky equatorial heat, cool tile floors in a homestay, soft volcanic sand, warm sea water year round, the splash of a sudden afternoon downpour…',
    see:   'What is the most incredible thing right in front of you right now…',
  },
  stories: [
    {
      location: '📍 Bali',
      question: 'Why are there little flower baskets everywhere?',
      body: 'In Bali you will see tiny woven palm-leaf baskets called "canang sari" on doorsteps, pavements, dashboards, even on top of statues. Every single one has been freshly made and offered that morning by a Balinese Hindu, usually a woman of the household. Inside there are flowers (one colour for each direction), a few grains of rice, sometimes a sweet or a cigarette, and a stick of incense. They are offerings to the gods, made three times a day. A typical family makes dozens every day, and the whole island is doing it at the same time.',
      thinkingQuestion: 'If you had to make a small offering every morning, what would you put in it, and who would it be for?',
    },
    {
      location: '📍 Borobudur, Java',
      question: 'What is the biggest Buddhist temple in the world?',
      body: 'Borobudur sits in the middle of Java and is the largest Buddhist monument on earth. It was built around the year 800, more than 1,200 years ago, by hand, with over 2 million volcanic stones. Then, around 1,000 years ago, the people of the region converted to Islam, and Borobudur was abandoned. The jungle slowly swallowed it. It stayed hidden for hundreds of years until it was rediscovered in 1814. Now it is a UNESCO site, and pilgrims walk clockwise up its nine levels at sunrise to reach the top.',
    },
    {
      location: '📍 Komodo Islands',
      question: 'Are Komodo dragons actually dangerous?',
      body: 'Yes. Komodo dragons grow up to 3 metres long and can weigh more than 70kg. They are fast, they can climb, they can swim between islands, and their saliva is full of bacteria so deadly that one bite can take down a water buffalo within a few days. They live only on a handful of Indonesian islands, nowhere else on earth. When you visit, a park ranger walks with you holding a long forked stick to gently push dragons away if they come too close. They do, sometimes.',
      olderOnly: true,
    },
    {
      location: '📍 Jakarta',
      question: 'Why is Indonesia building a brand new capital?',
      body: 'Jakarta is sinking. The city sits on a swampy delta and has been pumping so much groundwater out from below that whole districts have dropped several metres in the last 30 years. Parts of it now flood at high tide. So in 2019 the government decided to move the capital to a new city called Nusantara, deep in the jungle on the island of Borneo, hundreds of kilometres away. They are building it from scratch, planning for a million people. It is one of the most ambitious city-building projects of our lifetime.',
      olderOnly: true,
      thinkingQuestion: 'If you had to design a brand new capital city from nothing, what is the first thing you would build?',
    },
    {
      location: '📍 Yogyakarta, Java',
      question: 'What is a wayang shadow puppet show?',
      body: 'On Java and Bali, people have been telling stories with shadow puppets for over a thousand years. The puppets are flat, made of buffalo leather, beautifully painted, with long sticks for arms. A puppet master (called a "dalang") sits behind a white cotton screen with a lamp shining through, and moves the puppets so the audience on the other side sees their shadows dancing. The shows can last all night, sometimes from sunset to sunrise, telling huge old stories about gods and battles. A live gamelan orchestra clangs and chimes along beside the dalang the whole time.',
      thinkingQuestion: 'If you could put on your own shadow puppet show, what story would you tell?',
    },
  ],
  convoQuestions: [
    { question: 'What\'s the best thing you\'ve eaten in Indonesia so far?' },
    { question: 'What\'s the spiciest thing you\'ve tried? Out of 10, how brave were you?' },
    { question: 'What\'s one thing that surprises you about how Indonesian families live?' },
    { question: 'Have you found a favourite island or place so far? Why that one?' },
    { question: 'If you could bring one Indonesian habit home with you, what would it be?' },
    { question: 'Indonesia has hundreds of different ethnic groups and languages. What do you think holds it all together as one country?', olderOnly: true },
  ],
}

// ── THAILAND (premium, live) ─────────────────────────────────────
export const THAILAND_DATA: AdventurePackData = {
  slug: 'thailand',
  country: 'Thailand',
  flag: '🇹🇭',
  iso2: 'th',
  isFree: false,
  heroColour: 'bg-fuchsia-700',
  currency: {
    code: 'THB',
    name: 'Thai Baht',
    symbol: '฿',
    recommendedBudget: 400,
    budgetNote: 'Recommended: ฿400 (about £9)',
  },
  mapQuestions: [
    { question: 'Which continent is Thailand on?', answer: 'Asia, in the south-east, shaped a bit like an elephant\'s head 🌏' },
    { question: 'What is the capital of Thailand?', answer: 'Bangkok. Thais call it "Krung Thep", which means "City of Angels". Its full ceremonial name is the longest place name in the world, with over 160 letters.' },
    { question: 'Which countries border Thailand?', answer: 'Myanmar (Burma) to the west, Laos to the north-east, Cambodia to the east, and Malaysia to the south.' },
    { question: 'Has Thailand ever been colonised by Europeans?', answer: 'No, never. Thailand is the only country in South-East Asia that was never colonised. Thais are very proud of this, the country\'s old name "Siam" was changed to "Thailand" in 1939, which means "land of the free".', olderOnly: true },
    { question: 'What ocean and seas touch Thailand?', answer: 'The Andaman Sea on the west, the Gulf of Thailand on the east. Both connect to the Indian and Pacific Oceans.', olderOnly: true },
  ],
  phrases: [
    { english: 'Hello (said by a male / female)', nativeScript: 'สวัสดีครับ / ค่ะ', nativeLatin: 'Sawatdee khrap / kha', phonetic: 'sa-wat-DEE krap / kah', lang: 'th' },
    { english: 'Thank you', nativeScript: 'ขอบคุณ', nativeLatin: 'Khob khun', phonetic: 'kop KOON', lang: 'th' },
    { english: 'Please', nativeScript: 'กรุณา', nativeLatin: 'Karuna', phonetic: 'ka-ru-NAH', lang: 'th' },
    { english: 'How much?', nativeScript: 'เท่าไหร่?', nativeLatin: 'Tao rai?', phonetic: 'tow RYE', lang: 'th' },
    { english: 'Delicious!', nativeScript: 'อร่อย!', nativeLatin: 'Aroi!', phonetic: 'a-ROY', lang: 'th' },
    { english: 'Not spicy, please', nativeScript: 'ไม่เผ็ด', nativeLatin: 'Mai phet', phonetic: 'MY pet', lang: 'th' },
    { english: 'No problem / never mind', nativeScript: 'ไม่เป็นไร', nativeLatin: 'Mai pen rai', phonetic: 'my pen RYE', lang: 'th', olderOnly: true },
    { english: 'I would like…', nativeScript: 'ขอ…', nativeLatin: 'Khor…', phonetic: 'KOR', lang: 'th', olderOnly: true },
  ],
  foods: [
    { emoji: '🍜', name: 'Pad Thai', description: 'Stir-fried rice noodles with prawns or chicken, egg, peanuts, bean sprouts and a sweet-sour-salty sauce. Squeeze a lime over it, life changes.' },
    { emoji: '🍲', name: 'Tom Yum', description: 'A sour-spicy soup with prawns, lemongrass, lime leaves, galangal and chilli. Smells incredible. Will make you sweat.' },
    { emoji: '🥭', name: 'Mango sticky rice', description: 'Warm coconut sticky rice with slices of ripe mango on top, drizzled with salty coconut cream. The greatest dessert on earth, fight us.' },
    { emoji: '🍛', name: 'Green curry', description: 'Coconut milk and green chilli paste with chicken, Thai basil and little round Thai aubergines. Hotter than it looks.' },
    { emoji: '🥗', name: 'Som Tam', description: 'Green papaya salad pounded in a clay mortar with lime, fish sauce, peanuts and a lot of chilli. The classic Thai street snack.' },
    { emoji: '🍲', name: 'Khao Soi', description: 'Northern Thai curry noodle soup with crispy noodles on top, lime, pickles and chilli paste on the side. The signature dish of Chiang Mai.' },
  ],
  scavengerItems: [
    { emoji: '🛕', label: 'A tiny golden spirit house outside a shop or home' },
    { emoji: '🛺', label: 'A tuk-tuk weaving through traffic' },
    { emoji: '🟠', label: 'A monk in orange robes' },
    { emoji: '🐘', label: 'An elephant somewhere, real, statue, or painted on a wall' },
    { emoji: '🌸', label: 'A garland of marigolds offered at a shrine' },
    { emoji: '🥭', label: 'A street cart selling mango sticky rice' },
    { emoji: '🍜', label: 'A cook stir-frying in a wok over a roaring flame' },
    { emoji: '👑', label: 'A photo or portrait of the King in a shop or restaurant' },
    { emoji: '🐈', label: 'A temple cat' },
    { emoji: '🛶', label: 'A long-tail boat with a wooden propeller shaft', olderOnly: true },
    { emoji: '🪷', label: 'A lotus flower at a temple', olderOnly: true },
    { emoji: '🎭', label: 'A Thai script sign you can\'t read at all (it\'s a beautiful alphabet)', olderOnly: true },
  ],
  geoMatches: [
    { place: 'Bangkok',     emoji: '🏙️', description: 'The capital. Royal palaces, sky-high skyscrapers, floating markets, sky trains, and street food on almost every corner.' },
    { place: 'Chiang Mai',  emoji: '⛰️', description: 'The northern city in the mountains. Hundreds of temples, cooler weather, hill tribes nearby, and the home of khao soi noodles.' },
    { place: 'Phuket',      emoji: '🏝️', description: 'A big island in the south with turquoise water, hidden coves, and viewpoints over the Andaman Sea.' },
    { place: 'Ayutthaya',   emoji: '🏛️', description: 'Thailand\'s old capital, abandoned in 1767. Now a UNESCO site of crumbling brick temples, with one stone Buddha head wrapped in tree roots.' },
    { place: 'Krabi',       emoji: '🪨', description: 'Towering limestone cliffs rising straight out of the sea, jungle behind, white-sand beaches in front. The setting for many famous films.' },
    { place: 'Isaan',       emoji: '🌾', description: 'The huge north-east region. Rice fields, ancient Khmer temples, the spiciest food in the country, and the warmest welcome.' },
  ],
  senses: {
    smell: 'Lemongrass and chilli from a street wok, jasmine garlands at a shrine, frangipani, charcoal smoke, tropical rain on hot pavement, sometimes durian…',
    hear:  'The clatter of woks, scooter horns, "Sawatdee!" from every shop, temple bells, monks chanting at dawn, geckos, the rumble of monsoon thunder…',
    taste: 'Sweet, salty, sour and spicy all in one mouthful, sticky rice fingertips, the punch of fish sauce, cooling fresh coconut, mango that tastes like sunshine…',
    feel:  'Sticky heat that wraps around you, cool marble at a temple (shoes off), warm sea water, the breeze of a long-tail boat speeding across the bay…',
    see:   'What is the most incredible thing right in front of you right now…',
  },
  stories: [
    {
      location: '📍 Everywhere in Thailand',
      question: 'Why are there little dollhouses outside every building?',
      body: 'Those tiny ornate "houses" you see outside almost every Thai shop, home and hotel are called spirit houses. Thais believe each piece of land has its own spirit, and when humans build on the land, the spirits need somewhere of their own to live, otherwise they cause trouble. So they build a small house on a pedestal, decorate it, and leave daily offerings of food, drinks, flowers, even a tiny bottle of strawberry soda. A monk usually chooses the right spot, and the house must face the right way to keep the spirits happy.',
      thinkingQuestion: 'If a spirit lived on the land your home is built on, what is one offering you would leave it every day?',
    },
    {
      location: '📍 Bangkok',
      question: 'Why are monks dressed in orange?',
      body: 'You will see Buddhist monks everywhere in Thailand, walking in lines at sunrise with bowls, collecting food from people. Their orange robes are not random, the colour comes from a dye that was originally made from boiled jackfruit wood, and it represents simplicity, humility and giving up worldly things. Most Thai boys will spend at least a short time as a monk in their lifetime, sometimes just a week, sometimes years. It is seen as a way of making merit, both for themselves and for their family.',
    },
    {
      location: '📍 Across Thailand',
      question: 'What is Songkran?',
      body: 'Every April, Thailand celebrates its new year with Songkran, the world\'s biggest water fight. For three days, the whole country turns into a giant battle of buckets, water pistols and ice-cold hoses. Officially, the water represents washing away the old year. In practice, no one is dry, no one is safe, and it is hilarious. It started as a gentle ritual of sprinkling scented water on the hands of elders. It has grown into something else entirely.',
      thinkingQuestion: 'If your country had a national festival, what should it be about, and what would people do?',
    },
    {
      location: '📍 Ayutthaya',
      question: 'Why is there a Buddha head in a tree?',
      body: 'In the ruins of Ayutthaya, the old capital, there is one stone Buddha head completely wrapped in the roots of a fig tree. The story: Ayutthaya was a huge, wealthy city until 1767, when a Burmese army invaded, burned the city to the ground and smashed most of the Buddha statues. One head fell to the ground, and over the next 250 years a tree slowly grew around it, swallowing it into its roots. The tree is still alive, and the Buddha is still inside it.',
      olderOnly: true,
    },
    {
      location: '📍 Across Thailand',
      question: 'What is Muay Thai?',
      body: 'Muay Thai is the national sport of Thailand, a centuries-old kind of kickboxing where fighters use their fists, elbows, knees and shins. It started as the way Thai soldiers were trained for battle, hundreds of years ago. Every fight begins with a slow, graceful dance called the "wai khru ram muay", where the fighter pays respect to their teacher and to the spirits of the ring. Then traditional music plays through the whole fight, getting faster as the action heats up. Thai kids start training as young as 6 or 7, and the best fighters become national heroes.',
      olderOnly: true,
    },
  ],
  convoQuestions: [
    { question: 'What\'s the best thing you\'ve eaten in Thailand?' },
    { question: 'How spicy is too spicy for you, out of 10?' },
    { question: 'If you could spend a week as a monk, what do you think the hardest part would be?' },
    { question: 'What\'s one thing about how people behave here that is different from at home?' },
    { question: 'Have you found a favourite temple or place yet? What made it special?' },
    { question: 'Thais say "mai pen rai" (never mind, it\'s fine) a lot. Where could you use more of that attitude in your own life?', olderOnly: true },
  ],
}

// ── MALAYSIA (premium, live) ─────────────────────────────────────
export const MALAYSIA_DATA: AdventurePackData = {
  slug: 'malaysia',
  country: 'Malaysia',
  flag: '🇲🇾',
  iso2: 'my',
  isFree: false,
  heroColour: 'bg-amber-700',
  currency: {
    code: 'MYR',
    name: 'Malaysian Ringgit',
    symbol: 'RM',
    recommendedBudget: 50,
    budgetNote: 'Recommended: RM50 (about £8)',
  },
  mapQuestions: [
    { question: 'Which continent is Malaysia on?', answer: 'Asia. Specifically South-East Asia, just north of the equator 🌏' },
    { question: 'Malaysia is split into two parts. What are they?', answer: 'Peninsular Malaysia (joined to mainland Asia) and East Malaysia (on the island of Borneo). The two parts are about 600km apart, separated by the South China Sea.' },
    { question: 'What is the capital of Malaysia?', answer: 'Kuala Lumpur, often shortened to "KL". It means "muddy confluence", because it grew up where two muddy rivers meet.' },
    { question: 'Which country sits inside Malaysia?', answer: 'Singapore is a tiny island country joined to Peninsular Malaysia by a short bridge. They were the same country until 1965, when Singapore was separated.', olderOnly: true },
    { question: 'Malaysia shares an island with two other countries. Which?', answer: 'The island of Borneo is shared by Malaysia, Indonesia, and the tiny oil-rich kingdom of Brunei.', olderOnly: true },
  ],
  phrases: [
    { english: 'Hello', nativeScript: 'Helo / Salam', nativeLatin: 'Helo / Salam', phonetic: 'HEH-loh / sa-LAM', lang: 'ms' },
    { english: 'Thank you', nativeScript: 'Terima kasih', nativeLatin: 'Terima kasih', phonetic: 'tuh-REE-ma KAH-see', lang: 'ms' },
    { english: 'Please', nativeScript: 'Tolong', nativeLatin: 'Tolong', phonetic: 'TOH-long', lang: 'ms' },
    { english: 'How much?', nativeScript: 'Berapa?', nativeLatin: 'Berapa?', phonetic: 'buh-RAH-pa', lang: 'ms' },
    { english: 'Delicious!', nativeScript: 'Sedap!', nativeLatin: 'Sedap!', phonetic: 'suh-DAP', lang: 'ms' },
    { english: 'Goodbye', nativeScript: 'Selamat tinggal', nativeLatin: 'Selamat tinggal', phonetic: 'suh-LA-mat TING-gal', lang: 'ms' },
    { english: 'Eat already? (a friendly greeting)', nativeScript: 'Sudah makan?', nativeLatin: 'Sudah makan?', phonetic: 'SOO-dah MA-kan', lang: 'ms', olderOnly: true },
    { english: 'I would like…', nativeScript: 'Saya mahu…', nativeLatin: 'Saya mahu…', phonetic: 'SA-ya MA-hoo', lang: 'ms', olderOnly: true },
  ],
  foods: [
    { emoji: '🍚', name: 'Nasi lemak', description: 'Coconut rice with crispy fried anchovies, peanuts, boiled egg, cucumber, and spicy sambal. The national dish, eaten any time of day, usually for breakfast.' },
    { emoji: '🥞', name: 'Roti canai', description: 'A flaky, buttery flatbread tossed and stretched until paper-thin, then folded and pan-fried, served with curry or dhal for dipping.' },
    { emoji: '🍜', name: 'Char kway teow', description: 'Wide flat rice noodles stir-fried hard and fast over flame with prawns, Chinese sausage, egg, bean sprouts and chives. Best from a smoky hawker stall.' },
    { emoji: '🍲', name: 'Laksa', description: 'A spicy noodle soup. There are dozens of regional kinds. Penang assam laksa is sour, fishy and herby. Curry laksa is creamy with coconut. Both are amazing.' },
    { emoji: '🍢', name: 'Satay', description: 'Charcoal-grilled skewers of chicken or beef marinated in turmeric, served with thick peanut sauce, cucumber and rice cakes. Eaten by the dozen.' },
    { emoji: '🍧', name: 'Cendol', description: 'A cold dessert of shaved ice, coconut milk, palm sugar syrup and bright green jelly noodles made from rice flour. The perfect antidote to the heat.' },
  ],
  scavengerItems: [
    { emoji: '🏙️', label: 'The Petronas Twin Towers (or a souvenir of them)' },
    { emoji: '🍜', label: 'A hawker stall with stools so small you nearly miss them' },
    { emoji: '🕌', label: 'A mosque, a temple and a church within walking distance of each other' },
    { emoji: '🌴', label: 'A palm-oil plantation stretching to the horizon (from a car window)' },
    { emoji: '🐒', label: 'A monkey on a roof, fence or wire' },
    { emoji: '🌧️', label: 'A sudden afternoon thunderstorm out of a clear sky' },
    { emoji: '🍌', label: 'A type of banana you have never seen before' },
    { emoji: '☕', label: 'A "kopitiam" (old-school coffee shop) sign' },
    { emoji: '🛺', label: 'A trishaw (especially in Melaka, often decorated with flowers and speakers)' },
    { emoji: '🪁', label: 'A "wau bulan" moon kite (a Malaysian symbol you\'ll see on signs and money)', olderOnly: true },
    { emoji: '🦋', label: 'A huge tropical butterfly', olderOnly: true },
    { emoji: '📜', label: 'A sign in three different scripts (Latin, Chinese, Tamil) on the same wall', olderOnly: true },
  ],
  geoMatches: [
    { place: 'Kuala Lumpur', emoji: '🏙️', description: 'The capital. Skyscrapers next to colonial buildings next to mosques next to Chinese temples. The Petronas Twin Towers light up at night.' },
    { place: 'Penang',       emoji: '🥢', description: 'An island in the north-west, with the city of George Town. UNESCO heritage shophouses, colourful street art, and arguably the best food in Asia.' },
    { place: 'Borneo',       emoji: '🦧', description: 'East Malaysia, shared with Indonesia and Brunei. Rainforests with wild orangutans, the world\'s biggest flowers, and the highest mountain in South-East Asia.' },
    { place: 'Langkawi',     emoji: '🏝️', description: 'An archipelago of 99 islands in the Andaman Sea. Jungle-covered rocks rising out of the sea, eagles overhead, sandy beaches.' },
    { place: 'Melaka',       emoji: '🏛️', description: 'A small old port city on the west coast. Once ruled by Malays, Portuguese, Dutch and British. Red colonial buildings, river boats, and Peranakan houses.' },
    { place: 'Cameron Highlands', emoji: '🍃', description: 'A cool tea-growing region in the misty hills. Endless rows of bright green tea bushes, strawberry farms, and cool nights, a relief from the lowland heat.' },
  ],
  senses: {
    smell: 'Frying garlic and shrimp paste at a hawker stall, frangipani, durian (you will never forget it), incense from Chinese temples, monsoon rain on hot streets…',
    hear:  'The clang of woks, scooters revving, the call to prayer five times a day, Tamil pop blaring from a kopitiam radio, monsoon rain hammering on tin roofs…',
    taste: 'Coconut rice with crunchy peanuts, fiery sambal, sweet teh tarik (pulled milk tea), salty fried anchovies, cooling cendol, the punch of fresh chilli…',
    feel:  'Sticky humidity, the cool of an air-conditioned mall after the street, hot plastic stools at hawker centres, the soft splash of warm-sea waves…',
    see:   'What is the most incredible thing right in front of you right now…',
  },
  stories: [
    {
      location: '📍 Kuala Lumpur',
      question: 'Why does Malaysian food taste like three different countries at once?',
      body: 'Because it kind of is. Malaysia is home to three big communities living side by side: Malays (mostly Muslim, descended from people who have lived here for thousands of years), Chinese (whose ancestors came in the 1800s to work tin mines), and Indians (whose ancestors came mainly from Tamil Nadu to work rubber plantations). Each brought their own food, language, religion and festivals. Over time the cuisines borrowed from each other. So Malaysian food might use Chinese noodles, Indian curry spices and Malay coconut milk in the same dish, and it works.',
    },
    {
      location: '📍 Penang',
      question: 'Why is Penang so obsessed with food?',
      body: 'In George Town, the capital of Penang, food is a near-religion. Hawker stalls have been in the same families for three or four generations, with grandparents passing down a single noodle recipe perfected over 50 years. Most stalls only make one dish. Locals will queue 40 minutes for char kway teow at a particular stall but walk past three others. Streets are named after the food sold on them. The unofficial way to greet someone is "Eat already?" (Sudah makan?), and the answer is expected to be no, so you can join them.',
      thinkingQuestion: 'If your family was famous for cooking just one dish for the next 50 years, what should it be?',
    },
    {
      location: '📍 Borneo',
      question: 'What is the biggest flower in the world?',
      body: 'It grows in the rainforests of Borneo and Sumatra. The rafflesia can reach over a metre wide, weigh 10 kilos, and has no leaves, no stem and no roots, it is a parasite that grows out of a jungle vine. It blooms for just five days, then rots into a black puddle. And to top it off, it smells like rotting flesh, on purpose, to attract flies that pollinate it. People in Borneo trek through jungle for hours just to see one in bloom, then have to leave very quickly because of the smell.',
      olderOnly: true,
    },
    {
      location: '📍 Borneo',
      question: 'Who are the wild people of Borneo?',
      body: '"Orangutan" comes from the Malay words "orang" (person) and "hutan" (forest), so it literally means "person of the forest". They live wild only in Borneo and Sumatra, and they share about 97% of their DNA with humans. They are smart enough to use tools, build nests in trees every night, and they can recognise faces. Sadly, their forest is being cut down for palm oil plantations, and there may be only around 100,000 of them left in the wild. The Sepilok rehabilitation centre in Borneo rescues babies who have lost their mothers and teaches them how to climb and find food.',
      olderOnly: true,
      thinkingQuestion: 'Orangutans share 97% of our DNA. What is one human thing they do that surprises you most?',
    },
    {
      location: '📍 Anywhere in Malaysia',
      question: 'Why is one fruit banned in hotels?',
      body: 'Durian is a big, spiky green fruit that Malaysians call "the king of fruits". The flesh inside is sweet, creamy and rich, and some people would happily fight a tiger for one. The catch: it smells. Really smells. People have compared it to gym socks, blue cheese, rotting onions, or all three at once. The smell is so strong, and it clings to fabric so well, that you will see "No durian" signs in hotels, airports and trains all over South-East Asia. Whole shops sell nothing but durian. Try a piece if you dare, just maybe wash your hands afterwards.',
      thinkingQuestion: 'Imagine inventing a fruit that smells terrible but tastes amazing. Who would you trick into trying it first?',
    },
  ],
  convoQuestions: [
    { question: 'What\'s the best thing you\'ve eaten in Malaysia?' },
    { question: 'Did you try durian? On a scale of 1 to 10, how bad / good was it?' },
    { question: 'Malaysians speak Malay, English, Chinese and Tamil. How does it feel to be somewhere where everyone speaks several languages?' },
    { question: 'Which has been your favourite place so far, the city, the jungle, or the beach?' },
    { question: 'What\'s one thing Malaysians do better than back home?' },
    { question: 'Three big communities live side by side here, mostly peacefully. What do you think makes that work?', olderOnly: true },
  ],
}

// ── SPAIN (premium, live) ────────────────────────────────────────
export const SPAIN_DATA: AdventurePackData = {
  slug: 'spain',
  country: 'Spain',
  flag: '🇪🇸',
  iso2: 'es',
  isFree: false,
  heroColour: 'bg-red-700',
  currency: {
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    recommendedBudget: 20,
    budgetNote: 'Recommended: 20 €',
  },
  mapQuestions: [
    { question: 'Which continent is Spain on?', answer: 'Europe, in the south-west, on the Iberian Peninsula 🌍' },
    { question: 'What is the capital of Spain?', answer: 'Madrid. It sits almost exactly in the geographic middle of the country, on a high plateau.' },
    { question: 'What sea and ocean touch Spain?', answer: 'The Mediterranean Sea on the east and south, and the Atlantic Ocean on the north-west.' },
    { question: 'Which small country is completely inside Spain (almost)?', answer: 'Andorra and Portugal share its borders, but the tiny British territory of Gibraltar sits on the southern tip, an actual rock with monkeys on it.', olderOnly: true },
    { question: 'What is the highest mountain in mainland Spain?', answer: 'Mulhacén, 3,479 metres, in the Sierra Nevada of Andalusia. Tide Peak on the Canary Islands is even higher, at 3,715 metres on a volcano.', olderOnly: true },
  ],
  phrases: [
    { english: 'Hello', nativeScript: 'Hola', nativeLatin: 'Hola', phonetic: 'OH-lah', lang: 'es' },
    { english: 'Thank you', nativeScript: 'Gracias', nativeLatin: 'Gracias', phonetic: 'GRAH-thee-as', lang: 'es' },
    { english: 'Please', nativeScript: 'Por favor', nativeLatin: 'Por favor', phonetic: 'por fah-VOR', lang: 'es' },
    { english: 'How much?', nativeScript: '¿Cuánto cuesta?', nativeLatin: '¿Cuánto cuesta?', phonetic: 'KWAN-toh KWES-tah', lang: 'es' },
    { english: 'Delicious!', nativeScript: '¡Está buenísimo!', nativeLatin: '¡Está buenísimo!', phonetic: 'es-TAH bwen-EE-see-moh', lang: 'es' },
    { english: 'Goodbye', nativeScript: 'Adiós', nativeLatin: 'Adiós', phonetic: 'a-dee-OHS', lang: 'es' },
    { english: 'Excuse me', nativeScript: 'Perdón', nativeLatin: 'Perdón', phonetic: 'pair-DOHN', lang: 'es', olderOnly: true },
    { english: 'I would like…', nativeScript: 'Quisiera…', nativeLatin: 'Quisiera…', phonetic: 'kee-SYAIR-ah', lang: 'es', olderOnly: true },
  ],
  foods: [
    { emoji: '🥘', name: 'Paella', description: 'Saffron rice cooked in a huge flat pan with seafood, chicken, rabbit or vegetables. Real paella is from Valencia and is only eaten at lunch, never dinner.' },
    { emoji: '🍤', name: 'Tapas', description: 'Small dishes meant to be shared. Not a meal, a way of eating. Order three or four, share them all, then move to another bar and do it again.' },
    { emoji: '🍖', name: 'Jamón', description: 'Cured ham, sliced paper-thin. The best is jamón ibérico from black pigs that eat acorns, hung in cellars for years. Tastes nutty, salty and unbelievably savoury.' },
    { emoji: '🍩', name: 'Churros con chocolate', description: 'Fried dough sticks dipped in a cup of hot chocolate so thick a spoon stands up in it. Breakfast for grown-ups, after a big night out. Or for any kid, any time.' },
    { emoji: '🍅', name: 'Gazpacho', description: 'A cold tomato, pepper and cucumber soup, drunk from a glass on hot days in the south. Sounds wrong on paper, tastes like summer.' },
    { emoji: '🥚', name: 'Tortilla española', description: 'A thick potato omelette, served in slices. Eaten warm or cold, for breakfast, lunch or dinner. Spaniards argue over whether onion belongs in it, it does.' },
  ],
  scavengerItems: [
    { emoji: '🐂', label: 'A black silhouette of a bull on a hillside (the famous "Toro de Osborne" road sign)' },
    { emoji: '☀️', label: 'A whole town that goes quiet around 2pm for siesta' },
    { emoji: '🍷', label: 'An old man drinking wine at 11am at a tapas bar' },
    { emoji: '🌶️', label: 'A long string of dried red peppers hanging from a balcony' },
    { emoji: '🍊', label: 'An orange tree growing on a street' },
    { emoji: '🎸', label: 'A flamenco guitar or someone playing one in a square' },
    { emoji: '🚶', label: 'The "paseo", the evening stroll where the whole town walks in a circle around the main square' },
    { emoji: '🏛️', label: 'A plaza mayor (main square) with arcades all the way around' },
    { emoji: '🚂', label: 'An old white village clinging to a hillside (a "pueblo blanco")' },
    { emoji: '🏰', label: 'A castle or fortress on a hilltop (Spain has more castles than any country in Europe)', olderOnly: true },
    { emoji: '🕌', label: 'A horseshoe arch left over from the Moors (most easily seen in Andalusia)', olderOnly: true },
    { emoji: '💃', label: 'A flamenco poster outside a bar', olderOnly: true },
  ],
  geoMatches: [
    { place: 'Madrid',     emoji: '🎨', description: 'The capital, high on a plateau. Royal palace, world-class art (the Prado), late dinners, and a buzzy nightlife that does not start until midnight.' },
    { place: 'Barcelona',  emoji: '🏛️', description: 'Coastal Catalan city. Gaudí\'s mad buildings, the Sagrada Família still being built after 140 years, tapas, beaches and Gothic alleyways.' },
    { place: 'Andalusia',  emoji: '☀️', description: 'The hot, sun-baked south. Flamenco, white hilltop villages, orange trees in every square, and the Alhambra palace in Granada.' },
    { place: 'Basque Country', emoji: '🌊', description: 'The green, rainy north. Its own language and identity, world-famous restaurants, sea cliffs, and pintxos (Basque tapas) on every corner in San Sebastián.' },
    { place: 'Canary Islands', emoji: '🌋', description: 'A volcanic archipelago off the coast of Africa. Black sand beaches, year-round sunshine, and the tallest mountain in Spain on Tenerife.' },
    { place: 'Galicia',    emoji: '🐙', description: 'The wild green Atlantic north-west. Misty cliffs, bagpipes (yes, bagpipes), boiled octopus on wooden plates, and the end of the Camino pilgrim route.' },
  ],
  senses: {
    smell: 'Olive oil and garlic in a frying pan, jasmine in Andalusian patios, salty Mediterranean air, the leather of new boots in Toledo, fresh oranges on the trees…',
    hear:  'Late café chatter that goes on until 1am, flamenco clapping ("palmas"), church bells, the rolled "rr" in every conversation, scooters in narrow lanes…',
    taste: 'Salty fatty jamón, vinegary olives, sweet horchata, cold beer ("una caña") on a hot afternoon, chocolate so thick you eat it with a spoon, the spice of paprika…',
    feel:  'White-hot midday heat that makes you go inside, the relief of a cool tile floor, the breeze on a balcony at midnight, smooth pebbles on a Mediterranean beach…',
    see:   'What is the most incredible thing right in front of you right now…',
  },
  stories: [
    {
      location: '📍 Barcelona',
      question: 'Why has Gaudí\'s church been under construction for 140 years?',
      body: 'Antoni Gaudí started designing the Sagrada Família in 1882. He was so obsessed with it that he eventually moved into the workshop on site and refused to work on anything else. In 1926 he was hit by a tram on his way back from mass. He looked like a beggar in his old shabby clothes, so no one helped him at first, and he died a few days later. The church was still nowhere near finished, and Gaudí had only completed drawings for parts of it. They are STILL building it from his sketches and models, expecting to finish around 2026, 144 years after they started.',
      thinkingQuestion: 'Gaudí knew he would never live to see his church finished. Have you ever started something that you knew someone else would have to finish for you?',
    },
    {
      location: '📍 Across Spain',
      question: 'Why do Spaniards eat dinner at 10pm?',
      body: 'In Spain it is totally normal to sit down for dinner at 10pm, even with kids. Most restaurants do not even open for dinner until 8.30pm. One reason: in 1942 the dictator Franco decided to put Spain on Berlin time to align with Nazi Germany during the war, but Spain is geographically much further west, so the clocks are basically wrong. Lunchtime in Spain is solar noon in most of Europe. The whole rhythm of the day, the siesta, the late dinner, makes more sense if you imagine the clocks an hour earlier.',
    },
    {
      location: '📍 Granada',
      question: 'Why is there a palace with Arabic writing all over it?',
      body: 'For nearly 800 years, much of Spain was part of the Muslim world, ruled by people who came over from north Africa in the year 711. They called the region "Al-Andalus", which is where the modern name Andalusia comes from. They built the Alhambra in Granada in the 1300s, with carved plasterwork, fountains, courtyards and Arabic poetry written on the walls. In 1492, the Christian kings finally pushed the last Muslim rulers out, but the Alhambra was so beautiful that they kept it almost intact. You can still walk through it today and read the poems carved into the walls.',
      olderOnly: true,
    },
    {
      location: '📍 Buñol, Valencia',
      question: 'Why do thousands of people throw tomatoes at each other every August?',
      body: 'Every August, the small town of Buñol in Valencia holds "La Tomatina", the world\'s biggest food fight. For one hour, around 20,000 people pelt each other with 150,000 over-ripe tomatoes in the streets, until the whole town runs red. It started around 1945 from a small fight at a parade, with no one really sure why it happened, but it kept going year after year because everyone had fun. Now you have to buy a ticket. The town fire engines hose everyone down afterwards.',
      thinkingQuestion: 'If your town invented a yearly festival, what should everyone do for one hour, just for fun?',
    },
    {
      location: '📍 Madrid',
      question: 'What is the most famous painting in Spain?',
      body: 'In 1937, during the Spanish Civil War, the small town of Guernica in the Basque Country was bombed for hours by German and Italian planes helping the Spanish dictator Franco. Most of the town was destroyed and hundreds of civilians died. A Spanish artist living in Paris, Pablo Picasso, was so horrified that he painted a huge mural in black, white and grey, showing screaming people and animals, broken bodies, a crying woman holding a dead child. It is called "Guernica", it is over 3 metres tall and 7 metres wide, and it now lives in the Reina Sofía museum in Madrid. Picasso said it should stay outside Spain until democracy returned. It only came home in 1981.',
      olderOnly: true,
      thinkingQuestion: 'Picasso believed a painting could change how people feel about war. Do you think a picture can really change minds?',
    },
  ],
  convoQuestions: [
    { question: 'What\'s the best thing you\'ve eaten in Spain so far?' },
    { question: 'What\'s been the latest you\'ve eaten dinner here? Did you love it or hate it?' },
    { question: 'Spain has tons of regional identities. Have you noticed somewhere that felt very different from somewhere else?' },
    { question: 'What\'s one Spanish habit you\'d like to take home?' },
    { question: 'Have you tried to roll your "r"? Whose is best in our family?' },
    { question: 'Spanish kids stay up late and are part of grown-up nights out. What do you think the upsides and downsides of that are?', olderOnly: true },
  ],
}

// ── PORTUGAL (premium, live) ─────────────────────────────────────
export const PORTUGAL_DATA: AdventurePackData = {
  slug: 'portugal',
  country: 'Portugal',
  flag: '🇵🇹',
  iso2: 'pt',
  isFree: false,
  heroColour: 'bg-emerald-800',
  currency: {
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    recommendedBudget: 20,
    budgetNote: 'Recommended: 20 €',
  },
  mapQuestions: [
    { question: 'Which continent is Portugal on?', answer: 'Europe, in the far south-west corner, on the Iberian Peninsula 🌍' },
    { question: 'What is the capital of Portugal?', answer: 'Lisbon (Lisboa in Portuguese). It sits on the river Tagus, and is one of the oldest cities in Western Europe.' },
    { question: 'Which country is the only land neighbour of Portugal?', answer: 'Spain, which it shares its entire eastern and northern border with. The rest of the country is Atlantic Ocean.' },
    { question: 'Portugal has two island groups in the Atlantic. Name one.', answer: 'Madeira (south-west of Portugal, near Morocco) and the Azores (way out in the middle of the Atlantic, halfway to America).', olderOnly: true },
    { question: 'Which huge country across the ocean speaks Portuguese?', answer: 'Brazil. About 220 million people in Brazil speak Portuguese, far more than in Portugal itself, because of Portugal\'s history of colonising it 500 years ago.', olderOnly: true },
  ],
  phrases: [
    { english: 'Hello', nativeScript: 'Olá', nativeLatin: 'Olá', phonetic: 'oh-LAH', lang: 'pt' },
    { english: 'Thank you (said by male / female)', nativeScript: 'Obrigado / Obrigada', nativeLatin: 'Obrigado / Obrigada', phonetic: 'oh-bree-GAH-doo / -dah', lang: 'pt' },
    { english: 'Please', nativeScript: 'Por favor', nativeLatin: 'Por favor', phonetic: 'por fah-VOR', lang: 'pt' },
    { english: 'How much?', nativeScript: 'Quanto custa?', nativeLatin: 'Quanto custa?', phonetic: 'KWAN-too KOOSH-ta', lang: 'pt' },
    { english: 'Delicious!', nativeScript: 'Delicioso!', nativeLatin: 'Delicioso!', phonetic: 'de-lee-see-OH-zoo', lang: 'pt' },
    { english: 'Goodbye', nativeScript: 'Adeus', nativeLatin: 'Adeus', phonetic: 'a-DAY-oosh', lang: 'pt' },
    { english: 'Excuse me / sorry', nativeScript: 'Desculpe', nativeLatin: 'Desculpe', phonetic: 'desh-KOOL-peh', lang: 'pt', olderOnly: true },
    { english: 'I would like…', nativeScript: 'Eu queria…', nativeLatin: 'Eu queria…', phonetic: 'eh-oo keh-REE-ah', lang: 'pt', olderOnly: true },
  ],
  foods: [
    { emoji: '🥧', name: 'Pastéis de nata', description: 'Small flaky custard tarts with caramelised tops. Best eaten warm, dusted with cinnamon, with an espresso (a "bica"), at 9am in any pastelaria.' },
    { emoji: '🐟', name: 'Bacalhau', description: 'Salted dried cod. The Portuguese say there are 365 ways to cook it, one for every day of the year. Try "bacalhau à brás" (with eggs, potatoes and olives).' },
    { emoji: '🥪', name: 'Francesinha', description: 'A monster sandwich from Porto. Layers of cured meats, steak and sausage in bread, melted cheese on top, drowned in a hot beer-and-tomato sauce. Bring an appetite.' },
    { emoji: '🐟', name: 'Sardinhas grilhadas', description: 'Fresh sardines grilled over charcoal in the street, served with bread and salad. Eaten everywhere in summer, especially during the June saints\' festivals in Lisbon.' },
    { emoji: '🥬', name: 'Caldo verde', description: 'A simple soup of potato, kale and a slice of smoky sausage. Tastes like a Portuguese grandmother\'s kitchen on a damp winter day.' },
    { emoji: '🥖', name: 'Bifana', description: 'Thin slices of pork marinated in garlic and wine, slapped into a crusty roll. Often eaten with a beer at a counter, standing up. The perfect quick lunch.' },
  ],
  scavengerItems: [
    { emoji: '🟦', label: 'A wall covered in blue-and-white "azulejo" tiles' },
    { emoji: '🚋', label: 'A yellow tram clattering up a hill (especially the 28 in Lisbon)' },
    { emoji: '🐔', label: 'A "Galo de Barcelos" (a colourful rooster) statue or souvenir' },
    { emoji: '🥧', label: 'A pastelaria with a tray of fresh pastéis de nata in the window' },
    { emoji: '☕', label: 'Someone drinking a tiny espresso ("uma bica") standing at a counter' },
    { emoji: '⛵', label: 'A sea view (you are never far from one in Portugal)' },
    { emoji: '🪨', label: 'A pavement made of small black and white stones in a pattern (calçada portuguesa)' },
    { emoji: '🐟', label: 'A sardine grill smoking outside a restaurant' },
    { emoji: '🌳', label: 'A cork oak tree with its bark stripped off' },
    { emoji: '🎵', label: 'A poster for a "fado" performance', olderOnly: true },
    { emoji: '🏰', label: 'A castle or watchtower (Portugal has hundreds)', olderOnly: true },
    { emoji: '🌊', label: 'A surfer riding a huge wave (especially in Nazaré)', olderOnly: true },
  ],
  geoMatches: [
    { place: 'Lisbon',    emoji: '🛤️', description: 'The capital, built on seven hills above the river Tagus. Yellow trams, tiled houses, viewpoints ("miradouros") on every corner.' },
    { place: 'Porto',     emoji: '🍷', description: 'The northern city, on the river Douro. Famous for port wine cellars, the Francesinha sandwich, and a beautiful old town that tumbles down to the river.' },
    { place: 'Algarve',   emoji: '🏖️', description: 'The southern coast. Golden cliffs, hidden coves you reach by boat, fishing villages, and the best beach weather in Europe.' },
    { place: 'Madeira',   emoji: '🌋', description: 'A volcanic island off the coast of Africa. Cliff-edge hikes, year-round flowers, the wickerwork toboggan ride down from Monte, and the wine Shakespeare drank.' },
    { place: 'Azores',    emoji: '🌿', description: 'Nine islands far out in the Atlantic. Green volcanic craters, hot springs, whales offshore, and cheese made by cows that graze beside the sea.' },
    { place: 'Sintra',    emoji: '🏰', description: 'A cool, misty hill town near Lisbon. Bright yellow and red Pena Palace sitting on top of a forested peak like something out of a fairy tale.' },
  ],
  senses: {
    smell: 'Sardines on charcoal grills in the street, sea salt on the Atlantic wind, fresh pastry from a pastelaria, espresso at every café, cork in old shops…',
    hear:  'Fado music drifting from a doorway, the rattle of a yellow tram, seagulls, the slap of waves on cliffs, "obrigada" in soft hushed voices, church bells…',
    taste: 'Warm custard tarts, salty grilled sardines, sweet port wine (for the grown-ups), strong espresso, sweet roasted chestnuts in winter, the bite of garlic…',
    feel:  'Cool azulejo tiles under your hand, sun-warmed cliff stones, Atlantic spray, the bumpy "calçada" cobblestones underfoot, cool morning fog on a Sintra hill…',
    see:   'What is the most incredible thing right in front of you right now…',
  },
  stories: [
    {
      location: '📍 Lisbon',
      question: 'Why is half of Portugal covered in blue tiles?',
      body: 'Those blue-and-white painted tiles you see everywhere in Portugal are called "azulejos". The Portuguese got the idea from the Moors (Muslim rulers who lived here in the Middle Ages), then made it their own over 500 years. The blue colour became fashionable because it imitated expensive Chinese porcelain. The tiles are not just decoration, they keep buildings cool in summer, easy to clean, and they tell stories: many old churches and train stations have huge tiled panels showing battles, saints, or scenes of everyday life. Locals say a Portuguese building without azulejos feels naked.',
      thinkingQuestion: 'If you could cover one wall of your home with painted tiles telling a story, what story would you tell?',
    },
    {
      location: '📍 Lisbon, 1755',
      question: 'What was the worst day in Lisbon\'s history?',
      body: 'On the morning of 1 November 1755, while most of Lisbon was at mass for All Saints\' Day, a massive earthquake struck. Buildings collapsed. Forty minutes later, a huge tsunami swept up the river and flooded the lower town. Then fires broke out everywhere and burned for five days. About a third of the city was destroyed, and tens of thousands of people died. The disaster shocked Europe. The man rebuilding Lisbon, the Marquis of Pombal, designed an entirely new grid-pattern city with anti-earthquake "cage" buildings. That whole downtown area, the Baixa, was the world\'s first earthquake-proof district.',
      olderOnly: true,
    },
    {
      location: '📍 Nazaré',
      question: 'Where do people surf the biggest waves on earth?',
      body: 'In the small fishing village of Nazaré on the Atlantic coast. Just offshore there is an underwater canyon, the Nazaré Canyon, that funnels storm swells from deep ocean straight onto the cliffs. The result: in winter, the waves can hit 30 metres high, the height of a 10-storey building. Surfers from around the world come here every winter to be towed by jet ski onto these monsters. The Portuguese surfer Garrett McNamara made it famous in 2011 by riding a 24-metre wave, breaking the world record. People watch from the red lighthouse on the cliff.',
      olderOnly: true,
      thinkingQuestion: 'What is the scariest thing you would do for a world record? And what is one you would never even try?',
    },
    {
      location: '📍 Across Portugal',
      question: 'What is "saudade"?',
      body: '"Saudade" is a Portuguese word that does not really translate into English. It means a deep, sweet, slightly sad longing for someone or somewhere that is far away, or for a moment in the past that you can never get back. Portuguese people say it is at the heart of who they are. You can hear it in fado music, the soulful guitar songs you hear in old Lisbon bars at night. The Portuguese feel saudade for their lost empire, for emigrant family members in other countries, for childhood beaches. It is, basically, a kind of homesickness for things that never quite existed.',
      thinkingQuestion: 'Is there a place or a time in your life that you sometimes miss, even though it is gone? What do you miss about it?',
    },
    {
      location: '📍 Barcelos, northern Portugal',
      question: 'Why is a colourful rooster the symbol of Portugal?',
      body: 'You will see colourful pottery roosters everywhere in Portugal, in shops, on key rings, on tea towels. They come from a legend hundreds of years old. A pilgrim walking to Santiago was wrongly accused of stealing silver and sentenced to be hanged. As the judge sat down to a roast chicken dinner, the pilgrim called out: "if I am innocent, that rooster will stand up and crow." Right on cue, the cooked rooster on the judge\'s plate jumped up, flapped its wings, and crowed. The judge let the pilgrim go. Now the Galo de Barcelos is a Portuguese symbol of luck, honesty and faith.',
      thinkingQuestion: 'If you could pick an animal to be your country\'s lucky symbol, what would it be and why?',
    },
  ],
  convoQuestions: [
    { question: 'What\'s the best thing you\'ve eaten in Portugal so far?' },
    { question: 'How many pastéis de nata can you eat in one day? Are we going to find out?' },
    { question: 'What\'s one thing about Portugal that feels totally different from Spain?' },
    { question: 'Which place have you loved the most so far, and why?' },
    { question: 'If you could send a postcard to one person right now, who would it be and what would you write?' },
    { question: 'Portugal once ran an empire that stretched around the world, and now it is a small quiet country. What do you think that feels like as a nation?', olderOnly: true },
  ],
}

// ── COUNTRY REGISTRY ────────────────────────────────────────────
// One entry per country, including the not-yet-populated ones so
// the listing page shows them all (with a "Coming soon" badge).
export const PACK_META: AdventurePackMeta[] = [
  { slug: 'france',    country: 'France',    flag: '🇫🇷', iso2: 'fr', isFree: true,  heroColour: 'bg-brand-900',  status: 'live' },
  { slug: 'morocco',   country: 'Morocco',   flag: '🇲🇦', iso2: 'ma', isFree: false, heroColour: 'bg-amber-900',  status: 'live' },
  { slug: 'indonesia', country: 'Indonesia', flag: '🇮🇩', iso2: 'id', isFree: false, heroColour: 'bg-rose-700',   status: 'live' },
  { slug: 'thailand',  country: 'Thailand',  flag: '🇹🇭', iso2: 'th', isFree: false, heroColour: 'bg-fuchsia-700',status: 'live' },
  { slug: 'malaysia',  country: 'Malaysia',  flag: '🇲🇾', iso2: 'my', isFree: false, heroColour: 'bg-amber-700',  status: 'live' },
  { slug: 'spain',     country: 'Spain',     flag: '🇪🇸', iso2: 'es', isFree: false, heroColour: 'bg-red-700',    status: 'live' },
  { slug: 'portugal',  country: 'Portugal',  flag: '🇵🇹', iso2: 'pt', isFree: false, heroColour: 'bg-emerald-800',status: 'live' },
  { slug: 'japan',     country: 'Japan',     flag: '🇯🇵', iso2: 'jp', isFree: false, heroColour: 'bg-rose-800',   status: 'coming-soon' },
  { slug: 'vietnam',   country: 'Vietnam',   flag: '🇻🇳', iso2: 'vn', isFree: false, heroColour: 'bg-red-800',    status: 'coming-soon' },
  { slug: 'cambodia',  country: 'Cambodia',  flag: '🇰🇭', iso2: 'kh', isFree: false, heroColour: 'bg-indigo-800', status: 'coming-soon' },
  { slug: 'china',     country: 'China',     flag: '🇨🇳', iso2: 'cn', isFree: false, heroColour: 'bg-red-900',    status: 'coming-soon' },
  { slug: 'india',     country: 'India',     flag: '🇮🇳', iso2: 'in', isFree: false, heroColour: 'bg-orange-700', status: 'coming-soon' },
  { slug: 'sri-lanka', country: 'Sri Lanka', flag: '🇱🇰', iso2: 'lk', isFree: false, heroColour: 'bg-teal-800',   status: 'coming-soon' },
  { slug: 'nepal',     country: 'Nepal',     flag: '🇳🇵', iso2: 'np', isFree: false, heroColour: 'bg-stone-700',  status: 'coming-soon' },
  { slug: 'turkey',    country: 'Turkey',    flag: '🇹🇷', iso2: 'tr', isFree: false, heroColour: 'bg-red-700',    status: 'coming-soon' },
  { slug: 'egypt',     country: 'Egypt',     flag: '🇪🇬', iso2: 'eg', isFree: false, heroColour: 'bg-yellow-700', status: 'coming-soon' },
]

// Lookup table for fully-built packs.
const FULL_DATA: Record<string, AdventurePackData> = {
  france:    FRANCE_DATA,
  morocco:   MOROCCO_DATA,
  indonesia: INDONESIA_DATA,
  thailand:  THAILAND_DATA,
  malaysia:  MALAYSIA_DATA,
  spain:     SPAIN_DATA,
  portugal:  PORTUGAL_DATA,
}

export function getPackData(slug: string): AdventurePackData | null {
  return FULL_DATA[slug] ?? null
}

export function getPackMeta(slug: string): AdventurePackMeta | null {
  return PACK_META.find(p => p.slug === slug) ?? null
}
