// Full ISO 3166-1 country list, used wherever we need to identify a
// country that isn't necessarily one of the Adventure Pack countries
// (eg. the kid's home country on the Adventure Passport).
//
// Storing 2-letter ISO codes (alpha-2) is the standard. We group by
// continent so the picker can mirror the Adventure Packs continent-
// drill-down UX.
//
// This file is intentionally pure data — no React, no Supabase — so
// it's safe to import from both server and client components.

import type { Continent } from './adventurePackTypes'

export type CountryInfo = {
  iso2: string          // 2-letter ISO 3166-1 alpha-2 code, lowercase
  name: string          // English name (short form, the one travellers use)
  continent: Continent | 'Antarctica'
}

// Sorted alphabetically by name. Uses lower-case iso2 throughout so
// it can drop straight into flagcdn.com URLs.
export const COUNTRIES: CountryInfo[] = [
  { iso2: 'af', name: 'Afghanistan',                          continent: 'Asia' },
  { iso2: 'al', name: 'Albania',                              continent: 'Europe' },
  { iso2: 'dz', name: 'Algeria',                              continent: 'Africa' },
  { iso2: 'ad', name: 'Andorra',                              continent: 'Europe' },
  { iso2: 'ao', name: 'Angola',                               continent: 'Africa' },
  { iso2: 'ag', name: 'Antigua and Barbuda',                  continent: 'North America' },
  { iso2: 'ar', name: 'Argentina',                            continent: 'South America' },
  { iso2: 'am', name: 'Armenia',                              continent: 'Asia' },
  { iso2: 'au', name: 'Australia',                            continent: 'Oceania' },
  { iso2: 'at', name: 'Austria',                              continent: 'Europe' },
  { iso2: 'az', name: 'Azerbaijan',                           continent: 'Asia' },
  { iso2: 'bs', name: 'Bahamas',                              continent: 'North America' },
  { iso2: 'bh', name: 'Bahrain',                              continent: 'Asia' },
  { iso2: 'bd', name: 'Bangladesh',                           continent: 'Asia' },
  { iso2: 'bb', name: 'Barbados',                             continent: 'North America' },
  { iso2: 'by', name: 'Belarus',                              continent: 'Europe' },
  { iso2: 'be', name: 'Belgium',                              continent: 'Europe' },
  { iso2: 'bz', name: 'Belize',                               continent: 'North America' },
  { iso2: 'bj', name: 'Benin',                                continent: 'Africa' },
  { iso2: 'bt', name: 'Bhutan',                               continent: 'Asia' },
  { iso2: 'bo', name: 'Bolivia',                              continent: 'South America' },
  { iso2: 'ba', name: 'Bosnia and Herzegovina',               continent: 'Europe' },
  { iso2: 'bw', name: 'Botswana',                             continent: 'Africa' },
  { iso2: 'br', name: 'Brazil',                               continent: 'South America' },
  { iso2: 'bn', name: 'Brunei',                               continent: 'Asia' },
  { iso2: 'bg', name: 'Bulgaria',                             continent: 'Europe' },
  { iso2: 'bf', name: 'Burkina Faso',                         continent: 'Africa' },
  { iso2: 'bi', name: 'Burundi',                              continent: 'Africa' },
  { iso2: 'kh', name: 'Cambodia',                             continent: 'Asia' },
  { iso2: 'cm', name: 'Cameroon',                             continent: 'Africa' },
  { iso2: 'ca', name: 'Canada',                               continent: 'North America' },
  { iso2: 'cv', name: 'Cape Verde',                           continent: 'Africa' },
  { iso2: 'cf', name: 'Central African Republic',             continent: 'Africa' },
  { iso2: 'td', name: 'Chad',                                 continent: 'Africa' },
  { iso2: 'cl', name: 'Chile',                                continent: 'South America' },
  { iso2: 'cn', name: 'China',                                continent: 'Asia' },
  { iso2: 'co', name: 'Colombia',                             continent: 'South America' },
  { iso2: 'km', name: 'Comoros',                              continent: 'Africa' },
  { iso2: 'cg', name: 'Congo (Republic)',                     continent: 'Africa' },
  { iso2: 'cd', name: 'Congo (Democratic Republic)',          continent: 'Africa' },
  { iso2: 'cr', name: 'Costa Rica',                           continent: 'North America' },
  { iso2: 'ci', name: 'Côte d\'Ivoire',                       continent: 'Africa' },
  { iso2: 'hr', name: 'Croatia',                              continent: 'Europe' },
  { iso2: 'cu', name: 'Cuba',                                 continent: 'North America' },
  { iso2: 'cy', name: 'Cyprus',                               continent: 'Europe' },
  { iso2: 'cz', name: 'Czechia',                              continent: 'Europe' },
  { iso2: 'dk', name: 'Denmark',                              continent: 'Europe' },
  { iso2: 'dj', name: 'Djibouti',                             continent: 'Africa' },
  { iso2: 'dm', name: 'Dominica',                             continent: 'North America' },
  { iso2: 'do', name: 'Dominican Republic',                   continent: 'North America' },
  { iso2: 'ec', name: 'Ecuador',                              continent: 'South America' },
  { iso2: 'eg', name: 'Egypt',                                continent: 'Africa' },
  { iso2: 'sv', name: 'El Salvador',                          continent: 'North America' },
  { iso2: 'gq', name: 'Equatorial Guinea',                    continent: 'Africa' },
  { iso2: 'er', name: 'Eritrea',                              continent: 'Africa' },
  { iso2: 'ee', name: 'Estonia',                              continent: 'Europe' },
  { iso2: 'sz', name: 'Eswatini',                             continent: 'Africa' },
  { iso2: 'et', name: 'Ethiopia',                             continent: 'Africa' },
  { iso2: 'fj', name: 'Fiji',                                 continent: 'Oceania' },
  { iso2: 'fi', name: 'Finland',                              continent: 'Europe' },
  { iso2: 'fr', name: 'France',                               continent: 'Europe' },
  { iso2: 'ga', name: 'Gabon',                                continent: 'Africa' },
  { iso2: 'gm', name: 'Gambia',                               continent: 'Africa' },
  { iso2: 'ge', name: 'Georgia',                              continent: 'Asia' },
  { iso2: 'de', name: 'Germany',                              continent: 'Europe' },
  { iso2: 'gh', name: 'Ghana',                                continent: 'Africa' },
  { iso2: 'gr', name: 'Greece',                               continent: 'Europe' },
  { iso2: 'gl', name: 'Greenland',                            continent: 'North America' },
  { iso2: 'gd', name: 'Grenada',                              continent: 'North America' },
  { iso2: 'gt', name: 'Guatemala',                            continent: 'North America' },
  { iso2: 'gn', name: 'Guinea',                               continent: 'Africa' },
  { iso2: 'gw', name: 'Guinea-Bissau',                        continent: 'Africa' },
  { iso2: 'gy', name: 'Guyana',                               continent: 'South America' },
  { iso2: 'ht', name: 'Haiti',                                continent: 'North America' },
  { iso2: 'hn', name: 'Honduras',                             continent: 'North America' },
  { iso2: 'hk', name: 'Hong Kong',                            continent: 'Asia' },
  { iso2: 'hu', name: 'Hungary',                              continent: 'Europe' },
  { iso2: 'is', name: 'Iceland',                              continent: 'Europe' },
  { iso2: 'in', name: 'India',                                continent: 'Asia' },
  { iso2: 'id', name: 'Indonesia',                            continent: 'Asia' },
  { iso2: 'ir', name: 'Iran',                                 continent: 'Asia' },
  { iso2: 'iq', name: 'Iraq',                                 continent: 'Asia' },
  { iso2: 'ie', name: 'Ireland',                              continent: 'Europe' },
  { iso2: 'il', name: 'Israel',                               continent: 'Asia' },
  { iso2: 'it', name: 'Italy',                                continent: 'Europe' },
  { iso2: 'jm', name: 'Jamaica',                              continent: 'North America' },
  { iso2: 'jp', name: 'Japan',                                continent: 'Asia' },
  { iso2: 'jo', name: 'Jordan',                               continent: 'Asia' },
  { iso2: 'kz', name: 'Kazakhstan',                           continent: 'Asia' },
  { iso2: 'ke', name: 'Kenya',                                continent: 'Africa' },
  { iso2: 'ki', name: 'Kiribati',                             continent: 'Oceania' },
  { iso2: 'kp', name: 'North Korea',                          continent: 'Asia' },
  { iso2: 'kr', name: 'South Korea',                          continent: 'Asia' },
  { iso2: 'kw', name: 'Kuwait',                               continent: 'Asia' },
  { iso2: 'kg', name: 'Kyrgyzstan',                           continent: 'Asia' },
  { iso2: 'la', name: 'Laos',                                 continent: 'Asia' },
  { iso2: 'lv', name: 'Latvia',                               continent: 'Europe' },
  { iso2: 'lb', name: 'Lebanon',                              continent: 'Asia' },
  { iso2: 'ls', name: 'Lesotho',                              continent: 'Africa' },
  { iso2: 'lr', name: 'Liberia',                              continent: 'Africa' },
  { iso2: 'ly', name: 'Libya',                                continent: 'Africa' },
  { iso2: 'li', name: 'Liechtenstein',                        continent: 'Europe' },
  { iso2: 'lt', name: 'Lithuania',                            continent: 'Europe' },
  { iso2: 'lu', name: 'Luxembourg',                           continent: 'Europe' },
  { iso2: 'mo', name: 'Macao',                                continent: 'Asia' },
  { iso2: 'mg', name: 'Madagascar',                           continent: 'Africa' },
  { iso2: 'mw', name: 'Malawi',                               continent: 'Africa' },
  { iso2: 'my', name: 'Malaysia',                             continent: 'Asia' },
  { iso2: 'mv', name: 'Maldives',                             continent: 'Asia' },
  { iso2: 'ml', name: 'Mali',                                 continent: 'Africa' },
  { iso2: 'mt', name: 'Malta',                                continent: 'Europe' },
  { iso2: 'mh', name: 'Marshall Islands',                     continent: 'Oceania' },
  { iso2: 'mr', name: 'Mauritania',                           continent: 'Africa' },
  { iso2: 'mu', name: 'Mauritius',                            continent: 'Africa' },
  { iso2: 'mx', name: 'Mexico',                               continent: 'North America' },
  { iso2: 'fm', name: 'Micronesia',                           continent: 'Oceania' },
  { iso2: 'md', name: 'Moldova',                              continent: 'Europe' },
  { iso2: 'mc', name: 'Monaco',                               continent: 'Europe' },
  { iso2: 'mn', name: 'Mongolia',                             continent: 'Asia' },
  { iso2: 'me', name: 'Montenegro',                           continent: 'Europe' },
  { iso2: 'ma', name: 'Morocco',                              continent: 'Africa' },
  { iso2: 'mz', name: 'Mozambique',                           continent: 'Africa' },
  { iso2: 'mm', name: 'Myanmar',                              continent: 'Asia' },
  { iso2: 'na', name: 'Namibia',                              continent: 'Africa' },
  { iso2: 'nr', name: 'Nauru',                                continent: 'Oceania' },
  { iso2: 'np', name: 'Nepal',                                continent: 'Asia' },
  { iso2: 'nl', name: 'Netherlands',                          continent: 'Europe' },
  { iso2: 'nz', name: 'New Zealand',                          continent: 'Oceania' },
  { iso2: 'ni', name: 'Nicaragua',                            continent: 'North America' },
  { iso2: 'ne', name: 'Niger',                                continent: 'Africa' },
  { iso2: 'ng', name: 'Nigeria',                              continent: 'Africa' },
  { iso2: 'mk', name: 'North Macedonia',                      continent: 'Europe' },
  { iso2: 'no', name: 'Norway',                               continent: 'Europe' },
  { iso2: 'om', name: 'Oman',                                 continent: 'Asia' },
  { iso2: 'pk', name: 'Pakistan',                             continent: 'Asia' },
  { iso2: 'pw', name: 'Palau',                                continent: 'Oceania' },
  { iso2: 'ps', name: 'Palestine',                            continent: 'Asia' },
  { iso2: 'pa', name: 'Panama',                               continent: 'North America' },
  { iso2: 'pg', name: 'Papua New Guinea',                     continent: 'Oceania' },
  { iso2: 'py', name: 'Paraguay',                             continent: 'South America' },
  { iso2: 'pe', name: 'Peru',                                 continent: 'South America' },
  { iso2: 'ph', name: 'Philippines',                          continent: 'Asia' },
  { iso2: 'pl', name: 'Poland',                               continent: 'Europe' },
  { iso2: 'pt', name: 'Portugal',                             continent: 'Europe' },
  { iso2: 'qa', name: 'Qatar',                                continent: 'Asia' },
  { iso2: 'ro', name: 'Romania',                              continent: 'Europe' },
  { iso2: 'ru', name: 'Russia',                               continent: 'Europe' },
  { iso2: 'rw', name: 'Rwanda',                               continent: 'Africa' },
  { iso2: 'kn', name: 'Saint Kitts and Nevis',                continent: 'North America' },
  { iso2: 'lc', name: 'Saint Lucia',                          continent: 'North America' },
  { iso2: 'vc', name: 'Saint Vincent and the Grenadines',     continent: 'North America' },
  { iso2: 'ws', name: 'Samoa',                                continent: 'Oceania' },
  { iso2: 'sm', name: 'San Marino',                           continent: 'Europe' },
  { iso2: 'st', name: 'São Tomé and Príncipe',                continent: 'Africa' },
  { iso2: 'sa', name: 'Saudi Arabia',                         continent: 'Asia' },
  { iso2: 'sn', name: 'Senegal',                              continent: 'Africa' },
  { iso2: 'rs', name: 'Serbia',                               continent: 'Europe' },
  { iso2: 'sc', name: 'Seychelles',                           continent: 'Africa' },
  { iso2: 'sl', name: 'Sierra Leone',                         continent: 'Africa' },
  { iso2: 'sg', name: 'Singapore',                            continent: 'Asia' },
  { iso2: 'sk', name: 'Slovakia',                             continent: 'Europe' },
  { iso2: 'si', name: 'Slovenia',                             continent: 'Europe' },
  { iso2: 'sb', name: 'Solomon Islands',                      continent: 'Oceania' },
  { iso2: 'so', name: 'Somalia',                              continent: 'Africa' },
  { iso2: 'za', name: 'South Africa',                         continent: 'Africa' },
  { iso2: 'ss', name: 'South Sudan',                          continent: 'Africa' },
  { iso2: 'es', name: 'Spain',                                continent: 'Europe' },
  { iso2: 'lk', name: 'Sri Lanka',                            continent: 'Asia' },
  { iso2: 'sd', name: 'Sudan',                                continent: 'Africa' },
  { iso2: 'sr', name: 'Suriname',                             continent: 'South America' },
  { iso2: 'se', name: 'Sweden',                               continent: 'Europe' },
  { iso2: 'ch', name: 'Switzerland',                          continent: 'Europe' },
  { iso2: 'sy', name: 'Syria',                                continent: 'Asia' },
  { iso2: 'tw', name: 'Taiwan',                               continent: 'Asia' },
  { iso2: 'tj', name: 'Tajikistan',                           continent: 'Asia' },
  { iso2: 'tz', name: 'Tanzania',                             continent: 'Africa' },
  { iso2: 'th', name: 'Thailand',                             continent: 'Asia' },
  { iso2: 'tl', name: 'Timor-Leste',                          continent: 'Asia' },
  { iso2: 'tg', name: 'Togo',                                 continent: 'Africa' },
  { iso2: 'to', name: 'Tonga',                                continent: 'Oceania' },
  { iso2: 'tt', name: 'Trinidad and Tobago',                  continent: 'North America' },
  { iso2: 'tn', name: 'Tunisia',                              continent: 'Africa' },
  { iso2: 'tr', name: 'Turkey',                               continent: 'Asia' },
  { iso2: 'tm', name: 'Turkmenistan',                         continent: 'Asia' },
  { iso2: 'tv', name: 'Tuvalu',                               continent: 'Oceania' },
  { iso2: 'ug', name: 'Uganda',                               continent: 'Africa' },
  { iso2: 'ua', name: 'Ukraine',                              continent: 'Europe' },
  { iso2: 'ae', name: 'United Arab Emirates',                 continent: 'Asia' },
  { iso2: 'gb', name: 'United Kingdom',                       continent: 'Europe' },
  { iso2: 'us', name: 'United States',                        continent: 'North America' },
  { iso2: 'uy', name: 'Uruguay',                              continent: 'South America' },
  { iso2: 'uz', name: 'Uzbekistan',                           continent: 'Asia' },
  { iso2: 'vu', name: 'Vanuatu',                              continent: 'Oceania' },
  { iso2: 'va', name: 'Vatican City',                         continent: 'Europe' },
  { iso2: 've', name: 'Venezuela',                            continent: 'South America' },
  { iso2: 'vn', name: 'Vietnam',                              continent: 'Asia' },
  { iso2: 'ye', name: 'Yemen',                                continent: 'Asia' },
  { iso2: 'zm', name: 'Zambia',                               continent: 'Africa' },
  { iso2: 'zw', name: 'Zimbabwe',                             continent: 'Africa' },
]

// Quick lookup by iso2 (lowercase).
const COUNTRIES_BY_ISO2: Record<string, CountryInfo> = Object.fromEntries(
  COUNTRIES.map(c => [c.iso2, c]),
)

export function getCountryByIso2(iso2: string | null | undefined): CountryInfo | null {
  if (!iso2) return null
  return COUNTRIES_BY_ISO2[iso2.toLowerCase()] ?? null
}

export function isValidCountryIso2(value: unknown): value is string {
  return typeof value === 'string'
    && /^[a-zA-Z]{2}$/.test(value)
    && Object.prototype.hasOwnProperty.call(COUNTRIES_BY_ISO2, value.toLowerCase())
}
