import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { isPremiumTier } from '@/lib/profile'
import type { PermissionMode } from '@/lib/passport-types'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

const PERMISSION_MODES: PermissionMode[] = ['view', 'guided', 'creator']

// POST /api/family/children
// Creates a child row for the currently signed-in parent. RLS keeps
// strangers out, the premium check keeps free users out. qr_token is
// generated by the DB default (gen_random_uuid::text), so the client
// never sees it until it reads back.
export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json(
      { error: 'Please sign in.', signInUrl: '/login?next=/family' },
      { status: 401 },
    )
  }

  const { data: profile } = await supabase
    .from('profiles')
    .select('subscription_tier')
    .eq('id', user.id)
    .maybeSingle()
  if (!isPremiumTier(profile?.subscription_tier)) {
    return NextResponse.json(
      { error: 'Premium membership required.' },
      { status: 403 },
    )
  }

  let body: { name?: string; avatar?: string; permission_mode?: string; age_mode?: string } = {}
  try { body = await request.json() } catch {}

  const name = typeof body.name === 'string' ? body.name.trim() : ''
  if (!name || name.length > 60) {
    return NextResponse.json({ error: 'Name must be 1–60 characters.' }, { status: 400 })
  }

  const avatar = typeof body.avatar === 'string' && body.avatar.length > 0 && body.avatar.length <= 16
    ? body.avatar
    : '🧒'

  const permission_mode: PermissionMode =
    typeof body.permission_mode === 'string' && (PERMISSION_MODES as string[]).includes(body.permission_mode)
      ? (body.permission_mode as PermissionMode)
      : 'guided'

  const age_mode: 'younger' | 'older' =
    body.age_mode === 'younger' || body.age_mode === 'older'
      ? body.age_mode
      : 'older'

  const { data, error } = await supabase
    .from('children')
    .insert({
      parent_id: user.id,
      name,
      avatar,
      permission_mode,
      age_mode,
    })
    .select('id')
    .single()

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
  return NextResponse.json({ id: data.id })
}
